### ISSUE TITLE
[Gnome System Monitor] Title bar tabs labels are truncated

### ISSUE THREAD

**Issue by nevack** [lassekongo83/adw-gtk3#1]
![image](https://user-images.githubusercontent.com/8330119/150427050-19f758d5-6e48-4fb2-8c4d-c017604be6a8.png)
App Version: 41.0
Locale: en_US.UTF-8
Revision: https://github.com/lassekongo83/adw-gtk3/commit/c9b3ed3bba68824a3168bdff75aad4054039fd30

**Comment by DiegoMagdaleno** [comment]
Latest update in the main branch, cannot reproduce this bug anymore 
![image](https://user-images.githubusercontent.com/38844659/150562673-41498000-73d4-4332-a96b-58adcc7d72e2.png)

**Comment by nevack** [comment]
Fixed for me
