### ISSUE TITLE
Context Menus

### ISSUE THREAD

**Issue by mangini210** [lassekongo83/adw-gtk3#100]
Excellent theme! The only difference I notice are context menus. Can something be done about it?

![Screenshot from 2022-04-27 16-08-08](https://user-images.githubusercontent.com/14181749/165635404-83641a50-864a-4548-aa27-435c7946bb7b.png)
![Screenshot from 2022-04-27 16-07-50](https://user-images.githubusercontent.com/14181749/165635251-6be30e04-5726-4544-8286-8865ffc32e65.png)

**Comment by lassekongo83** [comment]
Unfortunately not. GTK3 and GTK4 are different when it comes to menus. Trying to mimic it would most likely cause breakage in various apps.

**Comment by mangini210** [comment]
Just to let you know I modified the context menus to look like libadwaita and I haven't see any breaking yet.
![menu](https://user-images.githubusercontent.com/14181749/167514085-01d92ac3-7d61-4c5f-a33e-f2db19b13ed4.png) 
![menu dark](https://user-images.githubusercontent.com/14181749/167514375-f90619a6-a3ea-4e87-ba61-237106a62dbb.png)

**Comment by davidphilipbarr** [comment]
Do you have a diff or PR for this I'd like to test it out, thanks.

**Comment by mangini210** [comment]
Sorry I'm new to this stuff. I only replaced the whole menus section in the gtk.css file with the one from the Orchis theme, lol. I then did some minor tweaks: increasing padding and border radius from menu items.

**Comment by davidphilipbarr** [comment]
I'm struggling a little a little to get the menu borders rounded with the shadows but i have this working in my .config/gtk.css

        menu, .menu, .context-menu { margin: 4px; padding: 6px 6px; }
        .csd menu, .csd .menu, .csd .context-menu { border: none; border-radius: 6px; }
        menu menuitem, .menu menuitem, .context-menu menuitem {margin: 0;border-radius: 6px;padding: 7px 6px;}
        menu separator {margin: 3px 0}

i'll try and integrate it into the sass and build at some point, but native gtk apps seem ok, electron apps not so much.

**Comment by mangini210** [comment]
Try this for the shadows:

```
.csd.popup decoration {
  box-shadow: 0 2px 2.4px -1px rgba(0, 0, 0, 0.2), 0 4px 3px 0 rgba(0, 0, 0, 0.14), 0 1px 6px 0 rgba(0, 0, 0, 0.12); }
```
What do you mean with electron apps? Can they be themed?

**Comment by mangini210** [comment]
I think this would be the whole thing:
```
menu, 
.menu, 
.context-menu { 
  margin: 4px; 
  padding: 6px 6px; 
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.08);
}

.csd menu, 
.csd .menu, 
.csd .context-menu { 
  border: none; 
  border-radius: 12px; 
}
    
menu menuitem, 
.menu menuitem, 
.context-menu 
menuitem {
  margin: 0;
  border-radius: 6px;
  padding: 7px 6px;}
    
menu separator { margin: 6px; }

.csd.popup decoration {
  border-radius: 12px; 
  box-shadow: 0 2px 2.4px -1px rgba(0, 0, 0, 0.2), 0 4px 3px 0 rgba(0, 0, 0, 0.14), 0 1px 6px 0 rgba(0, 0, 0, 0.12);
}
```

**Comment by davidphilipbarr** [comment]
cool looks like i was missing the popup decoration.

I'm just using global overrides, so i'll deal with the colours when i merge locally and create a pr see if that helps get this un-wonted ;) i think your separator margin is more accurate also. 

the electron apps like chrome and visual studio look like this:
![electron](https://user-images.githubusercontent.com/93874/168416424-0a331c91-de5f-4727-99ab-b5135e0cd253.png)

compared to this (gtk3 left, 4 right)

![Screenshot from 2022-05-14 08-41-31](https://user-images.githubusercontent.com/93874/168416460-64ff68b3-b5ac-47b1-9c91-95b4803f9a62.png)

I'm sure there is a way to target electron apps. I think the menus looks more consistent and don't cause and issues outside of electron apps, so would consider it an improvement?

**Comment by davidphilipbarr** [comment]
https://github.com/davidphilipbarr/adw-gtk3/tree/context-menu
