### ISSUE TITLE
[Epiphany] Back and Forward Buttons always seem to be off.

### ISSUE THREAD

**Issue by CleoMenezesJr** [lassekongo83/adw-gtk3#107]
![Captura de tela de 2022-05-05 14-04-59](https://user-images.githubusercontent.com/54215258/166985480-0aa72c76-7335-4e58-9999-465b2c8b58e5.png)

How it should be:
![Captura de tela de 2022-05-05 14-08-46](https://user-images.githubusercontent.com/54215258/166986091-12f718d0-6249-45d0-b916-74d708223fe2.png)

**Comment by lassekongo83** [comment]
Fixed in https://github.com/lassekongo83/adw-gtk3/commit/b1a780527ce96eaaa8f6d352a80ad74acb9bf1d9
