### ISSUE TITLE
not working in nautilus

### ISSUE THREAD

**Issue by tiktakgames** [lassekongo83/adw-gtk3#109]
that theme is not working in nautilus. what can i do?

**Comment by Xelphos** [comment]
Try restarting after applying it. That is what worked from me on Fedora 36, Nautilus 42.1.1

**Comment by lassekongo83** [comment]
> EDIT: Actually, there is some weirdness with it. Things like Nautilus, System Monitor, and GNOME Tweaks don't seem to like to theme if the theme is installed locally (~/.local/share/themes). Works just fine when installed globally (/usr/share/themes).

Can't reproduce in OpenSuse Tumbleweed. May just be an issue with Fedora, or some other overlooked setting.
