### ISSUE TITLE
Menus have no shadow/border at all + tabs color

### ISSUE THREAD

**Issue by joaquinvacas** [lassekongo83/adw-gtk3#11]
![Captura de pantalla de 2022-01-25 16-23-55](https://user-images.githubusercontent.com/4403750/151006020-dbe79632-efa4-4b3b-a63f-cac53f6bcb3e.png)

Using Nautilus 41.2 and latest git at 25/01/2022 16:00, menus have no border or shadow, so it feels like it's the same surface.

Also, tabs color don't feel like they are the ones being used.

![image](https://user-images.githubusercontent.com/4403750/151006510-9cd41160-58f5-4243-bd15-01cc897422ff.png)

"Imágenes" is the chosen one.

but actually, inactive windows instead have that nice feeling.

![image](https://user-images.githubusercontent.com/4403750/151006366-088d40ba-6da5-444d-a8ab-dd9ffcbb7354.png)

**Comment by SilverMarcs** [comment]
I think this issue is being tracked in #8 . So far, tabs in light theme have proper colors but dark not.

**Comment by joaquinvacas** [comment]
Yep, so let's report just the menus without shadows/borders issue. 👌
