### ISSUE TITLE
Nautilus selected thumbnails have  round borders

### ISSUE THREAD

**Issue by dasnoopy** [lassekongo83/adw-gtk3#111]
Nautilus 42.1  with adw-gtk3 compiled via AUR-git package on archlinux 64 bit;

Just a very minor aesthetic  issue (if  this is an issue!): check  the selections in the attached image (zoom it at least at 400% or more):
![screenshot](https://user-images.githubusercontent.com/296922/167170883-b91c5123-7b72-4d25-83a0-5294c4c67f18.jpg)

You will notice that, while the thumbnails have square corners, the blue selection have round borders: this cause  a black "spot" in all four angles;

imo,  also the selection should be squared...

Regards

**Comment by lassekongo83** [comment]
Fixed in https://github.com/lassekongo83/adw-gtk3/commit/b1a780527ce96eaaa8f6d352a80ad74acb9bf1d9
