### ISSUE TITLE
Gnome Console alternate styles not themed

### ISSUE THREAD

**Issue by flipflop97** [lassekongo83/adw-gtk3#114]
Gnome Console has alternate headerbar styles when running a remote connection or when running a command as root. These are not styled with the Adwaita theme. Would it be possible to theme these?

![normal](https://user-images.githubusercontent.com/13943260/167615692-1cd1f7bf-9bfd-437b-82b4-5e4b62d1056a.png)

![root](https://user-images.githubusercontent.com/13943260/167615803-bc9f750f-ff6a-4a2f-97b7-fd8f021b9dfe.png)

![remote](https://user-images.githubusercontent.com/13943260/167616485-e911d152-e564-4bda-bee4-ccdf1d1bcd08.png)

**Comment by lassekongo83** [comment]
I've tried, but I'm not entirely sure if the buttons are hardcoded or not. There's a `.root` css class in the headerbar, but with it I can only change the buttons borders a little bit, the rest just doesn't want to comply.

**Comment by lassekongo83** [comment]
Works in gtk inspector, but not when applied to the theme. I'm clueless as to why.

**Comment by nguyensang28** [comment]
I see that Console is now ported to GTK4 and libadwaita, so just wait until the distro packages that version and we don't need it anymore except those who uses distro that still ships with GTK3 Console
