### ISSUE TITLE
Unreadable elements in dark theme variant

### ISSUE THREAD

**Issue by stomar117** [lassekongo83/adw-gtk3#115]
The menus in the dark variant of the theme are unreadable,
![image](https://user-images.githubusercontent.com/57960301/167852098-f9d42f21-3e5b-4be0-bddd-2dc3f17abea4.png)
Also most of the gtk-3 applications have a white outline on the title-bar of the window,
![image](https://user-images.githubusercontent.com/57960301/167852415-ac5997f7-d10b-4cc4-a959-1a3942893540.png)

The theme was installed from the `aur`.

*Note: The theme worked perfectly fine earlier, but after a complete re-installation of the gnome desktop and the theme itself, the anomalies started showing up*

**Comment by stomar117** [comment]
> Try re-logging, or make sure that you also set the appearance to dark in gnome-control-center

I did reboot the system once before filing the issue...

> Also make sure you don't have any customization in `~/.config/gtk-3.0/gtk.css`

The file doesn't even exist on my system...

**Comment by jcornuz** [comment]
I had the same problem on Fedora 36 - the latest GTK update solved it for me...
