### ISSUE TITLE
Inconsistent banner notification/media control popups 

### ISSUE THREAD

**Issue by logant547** [lassekongo83/adw-gtk3#117]
### Describe the issue
Some popups in Files, Sushi (file previewer), and Videos use an old style instead of the new flat Libadwaita style.

### Screenshot(s)

![Screenshot from 2022-05-12 23-16-08](https://user-images.githubusercontent.com/45543257/168065348-37729830-b7bf-46d9-a087-6b9cf31a4543.png)
![Screenshot from 2022-05-12 23-18-28](https://user-images.githubusercontent.com/45543257/168065378-16425dcd-0e14-4362-b4a8-f05e665523f3.png)

### Versions

- OS and version: Fedora 36 (Workstation)
- GNOME Version: 42.1

### Settings

- [ ] I installed the theme from the tarball.
- [x] I installed the theme from git as a global install. (Installed in `/usr/share/themes`)
- [ ] I installed the theme from git as a local install. (Installed in `~/.local/share/themes`)
- [ ] I installed the theme from AUR.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [x] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.
- [ ] I did not read any of the above.

**Comment by lassekongo83** [comment]
I'm not entirely sure what those specific widgets look like in libadwaita, but I copied the current osd and app-notification styles from libadwaita, so let me know if anything's missing.

**Comment by logant547** [comment]
Yeah, I assume since they have no fallback style that they just go back to the old default Adwaita style... I don't really know much about CSS myself though.
