### ISSUE TITLE
Any chance of rounded corners to match libadwaita theme in Fedora 36

### ISSUE THREAD

**Issue by Dorro101** [lassekongo83/adw-gtk3#118]
Recently updated to Fedora 36. I am a bit OCD regarding the UI and try to use use flatpaks exclusively. I installed your themes from flathub. So far very happy. I am getting used to the pale lines used to separate panels, but hopefully there is a CSS tweak tool is in libadwaita's future. I would prefer the square bottom window corners to be rounded like the included apps using libadwaita such as Files, and Software...

![Screenshot from 2022-05-13 08-55-58](https://user-images.githubusercontent.com/54166678/168190885-425e1a4d-978d-46e7-b0d3-28186c839441.png)

In the screenshot, included apps Files and Software have rounded corners, included app Terminal does not so I am assuming it has not yet been updated to libadwaita and uses your local GTK3 theme, libreMenu is a flatpak, using the flatpak version of your theme and has square corners.

- Computer: Lenovo Thinkpad X1 Tablet Gen 3
- OS and version: Fedora 36
- GNOME Version: 42

- [X] I installed the theme from git as a local install. (Installed in `~/.local/share/themes`)
- [X] The theme is the latest available version/git commit.
- [X] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [X] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [X] Before opening this issue I logged out of GNOME and then logged back in again.

Thanks to your hard work, the consistency really helps with my sanity/'kopwurms'...

Ciao
Dorian

**Comment by lassekongo83** [comment]
Only libhandy GTK3 applications can have bottom rounded corners. Nothing can be done in the theme. (It's up to the apps to either be ported to libadwaita or libhandy.)
