### ISSUE TITLE
Add installation instructions for Fedora package

### ISSUE THREAD

**Issue by wdkevonfernando** [lassekongo83/adw-gtk3#122]
There is a [copr repo by user nickavem](https://copr.fedorainfracloud.org/coprs/nickavem/adw-gtk3/) which provides an easy way to install this theme system wide. It has two packages, which seem to either update at a new release (adw-gtk3) or regularly (adw-gtk3-git).
Adding something like this to the readme would be helpful for Fedora users:
```
Installation on Fedora:
- dnf copr enable nickavem/adw-gtk3
- dnf install adw-gtk3 or dnf install adw-gtk3-git
```
Also thank you for this theme.

**Comment by lassekongo83** [comment]
The git version of that repository is not up to date.

**Comment by dusansimic** [comment]
I think there is no point to having a git package for Fedora. It's highly unusual to have that kind of a package. On Arch it makes sense since all the work is handled by an AUR helper.
