### ISSUE TITLE
Search bar border accent color in dark mode remains blue with customized _palette.scss

### ISSUE THREAD

**Issue by LordKordus** [lassekongo83/adw-gtk3#126]
I customized the variables in _palette.scss to get a green accent. It works beautifully, but the border around search bar remains blue. This only occurs in dark mode. Can be reproduced in Nautilus or Evince for example.

![Snímek obrazovky z 2022-05-20 22-25-21](https://user-images.githubusercontent.com/105948237/169605909-638f3ed3-0b67-4e22-890f-1a00c2f64e69.png)
![Snímek obrazovky z 2022-05-20 22-25-30](https://user-images.githubusercontent.com/105948237/169605942-b262bb1d-8752-4013-b9dc-7cb1d7661327.png)

**Comment by lassekongo83** [comment]
Yeah, that color needs to be defined elsewhere. Edit: https://github.com/lassekongo83/adw-gtk3/blob/71bdba5340c96291ea062c53ffc06b24fd99ff89/gtk/src/adw-gtk3/gtk-3.0/_drawing.scss#L24 for now.
