### ISSUE TITLE
Firefox corner rendering

### ISSUE THREAD

**Issue by siwonpawel** [lassekongo83/adw-gtk3#128]
### Describe the issue

When Firefox is rendering the window elements ( customize -> enable titlebar (unchecked) ), the theme is not fully rounded. This problem does not exists when using default setting in gnome-tweaks application.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9118809/169753838-e87f391e-ae30-4d2d-a818-90f866fcf0ac.png)

### Versions

- OS and version: Fedora 36
- GNOME Version: 42
- Firefox 100.0.2 installed via Flatpak

### Settings

- [ ] I installed the theme from the tarball.
- [ ] I installed the theme from git.
- [ ] I installed the theme from AUR.
- [x] I installed the theme from elsewhere. (Where?)
-- [x] Fedora COPR
- [x] The theme is the latest available version/git commit.
- [x] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
https://github.com/lassekongo83/adw-gtk3/issues/92#issuecomment-1106630578
