### ISSUE TITLE
Titlebar height is slightly too tall

### ISSUE THREAD

**Issue by dalingrin** [lassekongo83/adw-gtk3#13]
![image](https://user-images.githubusercontent.com/71467/151229802-a53a597f-73d4-4445-bcce-4eb23265399c.png)

On the left is a GTK4 LibAdwaita native applications (Extension Manager) and on the right is Gtk3 Gnome Software

**Comment by lassekongo83** [comment]
Is this only with gnome-software? I don't have it installed and I can't reproduce much it in other apps. (Well, maybe only 1 pixel.) The headerbars height can vary depending on what kind of widgets they have.

**Comment by SilverMarcs** [comment]
Was this really fixed though? Headerbars are still slightly taller for me on all apps

**Comment by lassekongo83** [comment]
Not for me, so I guess it comes down to some other settings. (Fonts perhaps. I'm using Cantarell 11.)

**Comment by Mofiqul** [comment]
@lassekongo83 - I am also using same font but header bars still taller

**Comment by SilverMarcs** [comment]
Yeah Im using Cantarell 11 too. What other setting could it be, if at all?

**Comment by Mofiqul** [comment]
@lassekongo83 - just now updated the theme again and now its fixed.

**Comment by Mofiqul** [comment]
@SilverMarcs - I had to remove the themes from `/usr/share/themes` first. idk why

**Comment by SilverMarcs** [comment]
@Mofiqul Interesting. Mine was taller from a fresh install too but I'll try removing from that location later
