### ISSUE TITLE
[Console] Border inconsistency.

### ISSUE THREAD

**Issue by CleoMenezesJr** [lassekongo83/adw-gtk3#131]
### Describe the issue

Mainly in the lower edges, it is possible to notice that the app is possibly different round than proposed by the theme.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/54215258/170285583-eae46a5b-3b51-41f3-97f2-ddd88326d4ca.png)

### Versions

- OS and version: Fedora 36 Silverblue
- GNOME Version: 42

### Settings

- [ ] I installed the theme from the tarball.
- [x] I installed the theme from git.
- [ ] I installed the theme from AUR.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [x] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue, I logged out of GNOME and then logged back in again.

**Comment by CleoMenezesJr** [comment]
> Can't reproduce. You're not using the mutter rounded patch or something?

I'm using regular mutter version 42.1

**Comment by daudix-UFO** [comment]
@CleoMenezesJr I'm sorry, not about this issue, but, I really like your terminal prompt, how can I have one?

**Comment by CleoMenezesJr** [comment]
A few days ago I created a gtk.css that was conflicting. I will close it

**Comment by CleoMenezesJr** [comment]
> @CleoMenezesJr I'm sorry, not about this issue, but, I really like your terminal prompt, how can I have one?

PowerLevel10k

**Comment by daudix-UFO** [comment]
@CleoMenezesJr Thank you very much !
