### ISSUE TITLE
Dark mode active title bar too subtle for my eyes

### ISSUE THREAD

**Issue by johnfrombluff** [lassekongo83/adw-gtk3#132]
### Describe the issue

Firstly, *thank you* for this amazing work, I really appreciate your efforts.

I've run into a small usability issue. I often find myself closing or moving the wrong window because I think I'm mousing over the active window, but instead am operating on some other window (I use sloppy focus). So, could the difference between the active title bar and all the others be made a little larger please? And would it be possible for that difference to be user-configurable?

### Versions

- OS and version: Fedora 36
- GNOME Version: 42

Flatpak install of this theme.

### Settings

- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [ ] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
> And would it be possible for that difference to be user-configurable?

The goal is to add the same high contrast mode libadwaita have. In the end I want the user be able to change every color. But it is a lot of work getting there, so I can't say when that will happen. Maybe I can speed up making a high contrast theme though.

Meanwhile edit: `~/.config/gtk-3.0/gtk.css` and add:

```css
headerbar:backdrop, .titlebar:backdrop {
  background-color: black;
}
```

Change `black` to whatever color you want the backdrop state to have.

**Comment by lassekongo83** [comment]
There's a dark hc variant in the [adw-colors](https://github.com/lassekongo83/adw-colors) project which decreases the backdrop focus and adds a higher contrast border on the focused window. It's user configurable, so you can change basically anything with the some css.
