### ISSUE TITLE
Pop launcher not being themed properly 

### ISSUE THREAD

**Issue by rxchit** [lassekongo83/adw-gtk3#133]
### Describe the issue

Pop launcher not being themed properly 
Installed from AUR

### Screenshot(s)

![image](https://user-images.githubusercontent.com/86218252/170862592-8c6f5c23-337f-4bd9-8586-f4926e5a7a12.png)

### Versions

- OS and version: Manajro testing
- GNOME Version:  42

### Settings

- [ ] I installed the theme from the tarball.
- [ ] I installed the theme from git.
- [x] I installed the theme from AUR.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
Try any of the solutions here: https://github.com/EliverLara/Nordic/issues/152

This does not seem to be related to this gtk theme.
