### ISSUE TITLE
[Suggestion] Nord colour variation.

### ISSUE THREAD

**Issue by riquezjp** [lassekongo83/adw-gtk3#135]
Hi,
I know it's easy to apply a simple colour theme to gtk4 apps in libadwaita using `~/.config/gtk-4.0/gtk.css` & I've tried the [Nord example HERE](https://www.reddit.com/r/gnome/comments/tp3v7d/theming_in_libadwaita_is_pretty_nice/i28pug0/). & it looks nice, I enjoy the softer greys compared to the default.

Is there a way to use `adw-gtk3` + named colours (find & replace) to shift adw-gtk3 to match the Nord example?

If so, it would also mean other simple palette shifts could be possible using the named colours from then on.

On the face of it it seems _'all'_ that needs doing is the various background blacks changing to the blue/grey nord tones. (& of course when I say 'all' there might be more than I expect ;-) )

This would mean Gnome42 users can enjoy the consistent look `adw-gtk3` provides & themed palette changes.

![Screenshot from 2022-05-31 10-15-32](https://user-images.githubusercontent.com/10734045/171139044-1d693457-86da-4821-bed0-d139477471f8.png)

![Screenshot from 2022-05-31 10-16-09](https://user-images.githubusercontent.com/10734045/171139058-c516c0e5-0f8d-4c79-809b-79100bfbf309.png)

**Comment by lassekongo83** [comment]
This has now been implemented. Not all named colors from libadwaita are supported. See: https://github.com/lassekongo83/adw-gtk3/blob/main/customizing.md for more info.
