### ISSUE TITLE
When using adw-gtk3-dark, matplotlib shows up as adwaita light theme

### ISSUE THREAD

**Issue by j7126** [lassekongo83/adw-gtk3#137]
### Describe the issue

I have the adw-gtk3-dark theme enabled and for some reason matplotlib dialogs are showing up as with the adwaita light theme.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/35882868/172101328-abbbea05-3dfd-46e3-a002-1e3b04eb23f7.png)
![image](https://user-images.githubusercontent.com/35882868/172099830-22f78233-8563-4581-abd2-705013e03897.png)
![image](https://user-images.githubusercontent.com/35882868/172101464-a3613b1e-3d41-4592-9528-88a4c9605e6f.png)

### Versions

- OS and version: Fedora 36
- GNOME Version: 42.1
- matplotlib 3.5.2
- Python 3.10.4
- adw-gtk3 v2.0

### Settings

- [x] I installed the theme from the tarball.
- [ ] I installed the theme from git.
- [ ] I installed the theme from AUR.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
How do I even run this app? I installed python-matplotlib in arch. Typing either matplotlib or python-matplotlib in the terminal gives me command not found.

**Comment by j7126** [comment]
ah sorry I should have been more specific.

matplotlib is a python plotting library.

it can be used like the following:
python file `test.py`:
```python
import matplotlib.pyplot as plt
plt.plot([1, 2, 3], [1, 2, 3])
plt.show()
```
then run `python3 test.py`

**Comment by j7126** [comment]
at first I thought that this may just be an issue with matplotlib not respecting gtk themes by default, however I know that is not the cause of the issue as when the normal adwaita dark theme is enabled it does show up correctly

**Comment by lassekongo83** [comment]
The issue is that it's a GTK4 application. This theme only styles GTK3 apps. You can extract libadwaita and copy the gtk-4.0 folder to the corresponding theme folder. See: https://github.com/lassekongo83/adw-gtk3/issues/23
