### ISSUE TITLE
Changing accent color?

### ISSUE THREAD

**Issue by MindlessDreams** [lassekongo83/adw-gtk3#138]
Hello, is it possible to change the accent colors from blue to orange for example? Thank you!

**Comment by lassekongo83** [comment]
Create/edit `~/.config/gtk-3.0/gtk.css` and add `@define-color blue_3 @orange_4;`

`@orange_4` is from the theme [palette](https://github.com/lassekongo83/adw-gtk3/blob/main/gtk/src/adw-gtk3/gtk-3.0/_palette.scss), but you can replace it with any color you like.

**Comment by lassekongo83** [comment]
The shell theme is not part of gtk. You can do the same to `~/.config/gtk-4.0/gtk.css` as well. (However, add `@define-color accent_bg_color @orange_4;` instead.)

**Comment by MindlessDreams** [comment]
Thank you, much appreciated. Is there a way to get different accent colors for default and for prefer-dark modes? Thanks again!

**Comment by lassekongo83** [comment]
> default and for prefer-dark modes?

Not as far as I know. Maybe creating a bash script that replaces the gtk.css file and sets the color would be possible.

**Comment by soumyaDghosh** [comment]
Hii, I tried the same by adding that line.. but it didn't change the accent color.
