### ISSUE TITLE
Usage of gtkalpha (issues in gnome-tour for example)

### ISSUE THREAD

**Issue by bellegarde-c** [lassekongo83/adw-gtk3#14]
adw-gtk3 is using gtkalpha in many widgets. I guess this comes from libadwaita.

But, this does not seems to work correctly with GTK3. Run gnome-tour, the back button will be broken because there is two buttons inside an overlay and transparency defined in headerbar { button:not(.titlebutton) {}} applies.

This can be fixed locally but it's a more general issue, just created a test widget in glade with two buttons inside an overlay: same issue.

I guess gtkalpha(currentColor) usage in libadwaita is for recoloring API, your opinion ?

Is this that a bad idea to just replace all this gtkalpha() code by color definitions (as GTK3 will never support any recoloring API) ?

**Comment by lassekongo83** [comment]
That would be a lot of color values to keep track of. I'll have to think about it. Even if GTK3 won't support a recoloring API, using gtkalpha would make it easier to modify the theme to match the libadwaita color schemes.

**Comment by bellegarde-c** [comment]
This does not fixed the issue in gnome tour because is a special case **headerbar { button:not(.titlebutton) {}}**  using transparency as button color. Maybe replace it with headebar color ?


https://user-images.githubusercontent.com/57196916/152054012-95b14420-ee2f-4676-9e2e-a2c13b59dedc.mp4


BTW, it fixed the other part of my issue, thanks!
