### ISSUE TITLE
[Readme] Add instructions for contributors how to make flatpak

### ISSUE THREAD

**Issue by daudix-UFO** [lassekongo83/adw-gtk3#141]
I want to test various some not merged things on fedora silverblue, but I don't have any way to test it because all my apps are flatpak, it will be really helpful if we have an build instruction for flatpak theme

**Comment by lassekongo83** [comment]
I have no idea how to make flatpaks, but I suppose you could use https://github.com/refi64/stylepak for now.

**Comment by daudix-UFO** [comment]
Looks like what I need, thank you :)
