### ISSUE TITLE
Gnome shell doesnt follow the default accent color

### ISSUE THREAD

**Issue by Radical4ever** [lassekongo83/adw-gtk3#144]
Hi, this is for the colour-rework branch, is more like a request bc gnome shell doesnt follow the default accent color when selected. so is it possible to create a theme that can follow the accent color

- OS and version: [Fedora 36]
- GNOME Version: [42]

### Settings

- [ ] I installed the theme from the tarball.
- [x] I installed the theme from git.
- [ ] I installed the theme from AUR.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [x] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
Unfortunately gnome-shell is completely separate from gtk, so there's nothing I can do. You would have to grab https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/gnome-42/data/theme and then change in `_colors.scss` the variable `$selected_bg_color`. Then you have to parse the sass and put it in another theme folder, like for example: `~/.themes/my-shell-theme/gnome-shell/gnome-shell.css` (Plus all the image assets and other included files. Which you may also have to modify in inkscape to get your accent color.)

I don't know of an easier way. Maybe GNOME will get a color API in the next version... or the one after.

**Comment by lassekongo83** [comment]
> flatpak

If you're using the adw-gtk3 flatpak themes they aren't on the same branch yet.

**Comment by Radical4ever** [comment]
nevermind i used `sudo flatpak override --filesystem=xdg-config/gtk-3.0` and i made it work (what a simple detail 😂). but even if you have the flatpak theme installed you can make the apps use another theme installed locally using `sudo flatpak override` and sudo is bc its for all apps
