### ISSUE TITLE
Pixelated Rounded Corners of Highlighted Selection in the Libreoffice's Toolbar

### ISSUE THREAD

**Issue by truly-irham** [lassekongo83/adw-gtk3#145]
### Describe the issue

Rounded corners of the highlighted selection in the Libreoffice's Toolbar (including all Libreoffice suites) is pixelated (see Figure 1 and 2). However, this issue does not occur in the sidebar (see Figure 3 and 4).

### Screenshot(s)

![image](https://user-images.githubusercontent.com/83001686/174531630-0a5a9b79-fa02-4b12-b748-1ab108e3b4f8.png)
Figure 1: From toolbar in Libreoffice Writer

![image](https://user-images.githubusercontent.com/83001686/174531752-bfbfea3a-af20-4e5b-bdda-c01d4de206eb.png)
Figure 2: From toolbar in Libreoffice Calc

![image](https://user-images.githubusercontent.com/83001686/174531868-970c6ded-8993-4dab-9ce2-263752a57703.png)
Figure 3: From sidebar in Libreoffice Writer

![image](https://user-images.githubusercontent.com/83001686/174531968-95d07788-06b6-4f1b-8419-d98258bcb2d0.png)
Figure 4: From sidebar in Libreoffice Impress

### Versions

- OS and version: Arch Linux x86_64
- GNOME Version: 42.2
- adw-gtk3 Version: 1.9.r9.18070fb-1 (Installed from AUR: adw-gtk3-git)
- Libreoffice Version: 7.3.4.2 30(Build:2) (Installed as native package but also reproducible in flatpaks)

### Settings

- [ ] I installed the theme from the tarball.
- [ ] I installed the theme from git.
- [x] I installed the theme from AUR.
- [ ] I installed the theme from elsewhere. (Where?)
- [ ] The theme is the latest available version/git commit.
- [x] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
Looks like those widgets aren't visible in GTK inspector, and I'd assume that it's an issue with libreoffice and not the theme. (Something simple as buttons not supported aliasing.)

**Comment by truly-irham** [comment]
Aah I see. I guess this issue should be closed then. Thanks for the clarification. hmu if I should reopen this.
