### ISSUE TITLE
Glitch in gnucash 

### ISSUE THREAD

**Issue by jldark** [lassekongo83/adw-gtk3#148]
glitch in gnucash categories combobox (mouse over)  since v3 I switched back to v2 to get rid of the issue

### Screenshot(s)
V3.x
![Capture d’écran du 2022-07-09 14-33-57](https://user-images.githubusercontent.com/89602723/178134742-f1643515-49e8-4e70-ba4c-6ab3b9652cd8.png)
V2 
![Capture d’écran du 2022-07-10 08-55-51](https://user-images.githubusercontent.com/89602723/178134752-fbbf71f7-5f8e-42a5-8536-8419d80a9424.png)

### Versions

- OS and version: Arch latest
- GNOME Version: 42

Gnucash 4.11
### Settings

- [ ] I installed the theme from the tarball.
- [x] I installed the theme from git.
- [ ] I installed the theme from AUR.
- [ ] I installed the theme from elsewhere. (Where?)
- [ ] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
On which page can I access that combobox?

**Comment by jldark** [comment]
Create a new file and you'll get something like this 




Double click on one item :






Click on the arrow : 



Thanks for your reactivity !


Best regards,

Le dimanche 10 juillet 2022 10:12:51 (+02:00), Mattias a écrit :



On which page can I access that combobox?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


--

**Comment by gregorydk** [comment]
This bug still happens in GnuCash 5.x

Can this fix be implemented?

`gnc-id-sheet-list { background-color: @window_bg_color; }`
