### ISSUE TITLE
PayPal email for payout from Pling.com / gnome-looks.

### ISSUE THREAD

**Issue by KushagraKarira** [lassekongo83/adw-gtk3#149]
Hi, I've been maintaining the project on gnome-looks and there seems to be some payout,
![image](https://user-images.githubusercontent.com/36698785/178135941-efa02797-050f-4f35-b32e-044a6af876d3.png)
will need an paypal email.

**Comment by lassekongo83** [comment]
Can you disable payouts? I don't have Paypal and have no desire to get one.

**Comment by KushagraKarira** [comment]
okay, i'll disable them
