### ISSUE TITLE
Geary: Add account dialog rounded borders

### ISSUE THREAD

**Issue by bellegarde-c** [lassekongo83/adw-gtk3#151]
In Geary "Accounts" dialog, clicking on a row to add a new button makes the HeaderBar roundness disabled while animated.

For information, Geary is replacing the GtkHeaderBar on the fly when the GtkStack current child is changed.

**Comment by lassekongo83** [comment]
What kind of element is it replacing it with? It all happens so fast so I can't see the element name in the inspector.

**Comment by lassekongo83** [comment]
Found out that the issue is with the transition animation. I simply need to set the transition properties.

**Comment by bellegarde-c** [comment]
Awesome, thanks for your work!
