### ISSUE TITLE
Nautilus list view: file selected color is grey (not blue)

### ISSUE THREAD

**Issue by riquezjp** [lassekongo83/adw-gtk3#152]
### Describe the issue

When selecting nautilus files in List View the selected bg colour is grey, not blue. In icon view it is blue.
Also, there is a _very_ faint line separating each row in the list view.

To be honest, I have been 'messing around' with themes, so this could be an error on my part,  but after detailed checking & then re-installing adw-gtk3, I still see this issue. It does not happen with any other theme. 
I have an older version (first version with named colours) of adw-gtk3 which I renamed & keep in ~/themes for testing/dev & that version does not have this problem.

### Screenshot(s)

![Screenshot from 2022-07-14 17-25-44](https://user-images.githubusercontent.com/10734045/179031182-d26e7358-a6c0-492b-9a1e-982e357c9e4c.png)

![Screenshot from 2022-07-14 17-26-32](https://user-images.githubusercontent.com/10734045/179031230-3b8ad749-1cb1-4632-9d3c-6f7740296732.png)

### Versions

- OS and version: [e.g Fedora 36] Manajro 21.3.3
- GNOME Version: [e.g 42] 42.2

### Settings

- [ ] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [x] I installed the theme from elsewhere. (Where?) PAMAC
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by riquezjp** [comment]
Thanks for your quick response. But it was blue before right? I'm not imagining that...? 

Ive been working on getting the blue to change to manjaro green & it was easily possible with the named colours update. I am using `accent_bg_color` in  my ~/.themes copy, but I guess the latest adw-gtk3 is not using that for Nautilus selected. it caused me some confusion, but as long as I'm not going crazy, that's ok!!

**Comment by lassekongo83** [comment]
Yeah it used the accent color before I changed it. You can change it back in your gtk.css:

```css
.nautilus-list-view .view:selected {
  background-color: @accent_bg_color;
  color: white;
}
.nautilus-list-view .view:selected:hover {
  background-color: @accent_bg_color;
}
```
