### ISSUE TITLE
Theme problems in Timeshift, Gparted

### ISSUE THREAD

**Issue by KaspianDev** [lassekongo83/adw-gtk3#153]
### Describe the issue
Timeshift, gparted and other system apps have broken theming when using adw-gtk3-dark.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/34658474/179355331-dcfac0e3-fd55-4dc3-8bf5-7449f6aa52d0.png)

### Versions

- OS and version: Manjaro Rolling (testing)
- GNOME Version: 42.2

### Settings

- [X] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [X] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [X] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [X] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by KaspianDev** [comment]
All other apps (flatpaks too) look totally correct.

**Comment by lassekongo83** [comment]
These apps run as root, and all look fine to me when installed in `/usr/share/themes/`.

**Comment by KaspianDev** [comment]
> These apps run as root, and all look fine to me when the theme is installed in `/usr/share/themes/`. Do the same issues occur if you install the theme in a new user profile?
> 
> Also if I'm not mistaken, Manjaro already have adw-gtk3 installed by default, so there may be some conflicts if you installed it from the tarball.

when i place theme only for user, most apps look broken

**Comment by KaspianDev** [comment]
i deleted git version of adw-gtk3 and installed one from manjaro, issue stays the same.

**Comment by lassekongo83** [comment]
Did you try creating a new user profile? Sometimes resetting everything to default can fix the issue, then you'll know you have a corrupted user profile (with my guess some broken config file or environment variable).

**Comment by KaspianDev** [comment]
> Did you try creating a new user profile? Sometimes resetting everything to default can fix the issue, then you'll know you have a corrupted user profile (with my guess some broken config file or environment variable).

actually its the other way around, running stuff as user works perfectly

opening any app by sudo breaks the theme

**Comment by lassekongo83** [comment]
Doesn't pamac install packages as root?

**Comment by KaspianDev** [comment]
> Doesn't pamac install packages as root?

it installs apps for system, not all of them require root user

gparted does for example

**Comment by lassekongo83** [comment]
Then I would assume pamac installed the theme in `/usr/share/themes/`, which should make all root apps use the theme. So the only conclusion I can come to is that it's an issue with Manjaro, or some missed user configuration.

1. Check: `~/.config/gtk-3.0/settings.ini` AND `/etc/gtk-3.0/settings.ini` and make sure it doesn't contain `gtk-theme-name`.
2. Check: `~/.config/gtk-3.0/ AND `/etc/gtk-3.0/` and make sure there are no files named `gtk.css`.
3. Run `env` and see if there's any `GTK_THEME` environment variable. If there is it needs to be unset. `unset GTK_THEME`

**Comment by KaspianDev** [comment]
Hey, I was able to resolve it by reinstalling adw-gtk3 and putting it in both user and root directories

Because otherwise we have these scenarios
theme installed for system, theme not installed for user -> broken theming for non root apps
theme installed on user, theme not installed for system -> broken theming for root apps

I think `mount --bind` to /usr/share/themes/adw-gtk3-dark might've ben the first flaw i made

**Comment by KaspianDev** [comment]
Additionally, now apps ran as root ignore custom accent colors i set (only them).
@lassekongo83 is that normal?

**Comment by lassekongo83** [comment]
Root apps probably need `/etc/gtk-3.0/gtk.css` for custom colors.
