### ISSUE TITLE
Does not support GTK2 apps

### ISSUE THREAD

**Issue by gjask** [lassekongo83/adw-gtk3#154]
### Describe the issue
Gtk2 apps do not respect this theme.

I know this is more of feature request than bug report but I wouldn't mind if gtk2 apps at least kept adwaita look from GTK3. However as adw-gtk3 doesn't seem to support GTK2 they default to GTK2 default theme which is much bigger eye sore. Adw and gtk3 adwaita differences are not that painful as this is.

#### Default Adwaita theme
![obrazek](https://user-images.githubusercontent.com/3306648/179499098-297d0f3d-751d-4867-b23c-80e705b63426.png)
#### Adw-gtk3 theme
![obrazek](https://user-images.githubusercontent.com/3306648/179499136-7ba02cc6-ea00-49f1-92bc-19b479267575.png)

### Versions

- OS and version: Fedora 36
- GNOME Version: 42

### Setting

- [x] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [ ] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by gjask** [comment]
I thought about it briefly and decided that I don't mind after all. Actually it may finally push me to find modern alternatives for these few gtk2 apps I still use.

**Comment by lassekongo83** [comment]
https://github.com/lassekongo83/adw-gtk3/issues/84#issuecomment-1093162864
