### ISSUE TITLE
Epiphany: Scrollbar is broken

### ISSUE THREAD

**Issue by CleoMenezesJr** [lassekongo83/adw-gtk3#157]
https://user-images.githubusercontent.com/54215258/180631419-4906ec33-244c-4b66-ab65-81a47a12dd37.mp4

https://user-images.githubusercontent.com/54215258/180631417-0abb6eae-e202-4374-8213-76fbd255bc16.mp4

### Versions

- OS and version: Fedora Silverblue
- GNOME Version: 42

### Settings

- [x] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [ ] The theme is the latest available version/git commit.
- [x] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
Already fixed, but the flathub version of the theme is not on the latest version yet.

**Comment by CleoMenezesJr** [comment]
Thank you, I just sent a PR updating the new version.
