### ISSUE TITLE
Nautilus search refinement options too large

### ISSUE THREAD

**Issue by Mel34** [lassekongo83/adw-gtk3#160]
### Describe the issue

Nautilus search refinement options don't fit into the search box, they're large enough to "spill" over the top and bottom of it.

### Screenshot(s)
![Screenshot from 2022-08-03 22-37-47](https://user-images.githubusercontent.com/13254332/182638983-eaa7c67f-27a4-42ef-90c8-10484b3f7c0b.png)

![Screenshot from 2022-08-03 22-38-15](https://user-images.githubusercontent.com/13254332/182638992-c4efca59-5959-4f3e-8590-4eb45217d0c3.png)

### Versions

- OS and version: Archlinux
- GNOME Version: 42.3
- Nautilus 42.2

### Settings

- [ ] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
Is this some sort of extension? I'm unable to get it to appear when searching.
