### ISSUE TITLE
Black corners in "Legacy Applications"

### ISSUE THREAD

**Issue by nellfs** [lassekongo83/adw-gtk3#165]
### Screenshots
- On Discord: 
![image](https://user-images.githubusercontent.com/59851660/185618899-f650c8ae-6b6c-4f9e-a6b1-317e3a18273c.png)

- On Gnome-terminal:
![image](https://user-images.githubusercontent.com/59851660/185619324-372274ac-a2b5-44a6-942e-9f40212adccc.png)

As you can see the legacy window has black pixels in the corners, it can be hard to notice
(It happens on top left and top right)

### Versions

- OS: Manjaro 21.3.6
- GNOME 42

### Settings

- [x] I installed the theme from the tar.xz file.
- [x] The theme is the latest version [adw-gtk3 v3.6]
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
Unfortunately nothing can be done about it. It's simply a legacy limitation.
