### ISSUE TITLE
Bluetooth transfer window not themed

### ISSUE THREAD

**Issue by Coosta6915** [lassekongo83/adw-gtk3#166]
### Describe the issue

The Bluetooth transfer window doesn't follow the `adw-gtk3` theme. You can open the window by running `bluetooth-sendto`.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/90425490/185753763-bb612c37-9262-4b60-bfac-6c44cad4bed5.png)

![image](https://user-images.githubusercontent.com/90425490/185753302-a43212da-dff3-48e3-bbe3-69e2cf38150b.png)

### Versions

- OS and version: Arch Linux
- GNOME Version: 42.4 (Wayland)

The output of `pacman -Qo $(which bluetooth-sendto)` is `/usr/bin/bluetooth-sendto is owned by gnome-bluetooth-3.0 42.2-1`

### Settings

- [ ] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [x] I installed the theme from elsewhere. (Where?)
>[AUR](https://aur.archlinux.org/packages/adw-gtk3)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
>I don't have Flatpak installed on my system
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
It's a GTK4 app. Follow: https://github.com/lassekongo83/adw-gtk3/blob/main/gtk4.md
