### ISSUE TITLE
Remove all backdrop states except on toolbars

### ISSUE THREAD

**Issue by robxnano** [lassekongo83/adw-gtk3#169]
While I was making some changes I found that the real libadwaita theme only uses backdrop states for items on headerbars and toolbars. Would it be possible to do the same here? It would help ensure consistency between old and new applications, and I think it would also look better to not dim the application's main content.

**Comment by lassekongo83** [comment]
Tabs also have a backdrop state from what I can see. Also focused elements and selected text.
