### ISSUE TITLE
Doesn't preserve dark style when on Ubuntu with Yaru accent theme

### ISSUE THREAD

**Issue by yellowgh0st** [lassekongo83/adw-gtk3#172]
### The issue

Shell doesn't preserve dark style. When adw-gtk3 is used on Ubuntu with Yaru accent theme content like clock, aggregated menu become light instead of dark.

### Screenshot(s)

...

### Versions

- OS and version: Ubuntu 22.10 (Kinetic Kudu) Daily Build
- GNOME Version: 43.beta

### Settings

- [ ] I installed the theme from the tar.xz file.
- [x] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
> Shell

The shell theme is not touched in this theme. Ubuntu's accent color changer completely changes the theme to another one.

**Comment by yellowgh0st** [comment]
Yes, you're right but in best scenario this should provide workaround.

**Comment by yellowgh0st** [comment]
![Screenshot from 2022-08-31 07-14-40](https://user-images.githubusercontent.com/34014106/187597827-847b6c2f-9153-4e0f-8d22-286c5898152a.png)

GTK3 gedit is dark, yet clock indicator remains light

**Comment by yellowgh0st** [comment]
I believe few extra classes might fix this scenario.
