### ISSUE TITLE
Issues with new tabs

### ISSUE THREAD

**Issue by zoli111** [lassekongo83/adw-gtk3#175]
### Describe the issue

I tried the latest commit with regularly used applications. It looks good but there are some problems.

### Screenshots

Nautilus: The tabbar has no background, and has a border on the bottom, so moving tabs looks like this.
![nautilus](https://user-images.githubusercontent.com/57037245/191824469-eff2cf26-a173-4e72-8799-305982150363.png)

Gnome Terminal: Tabs have no left padding. There are also problems with inactive state.
![terminal](https://user-images.githubusercontent.com/57037245/191825480-0c3e029b-1486-4405-b725-3562e8a23252.png)
![terminal2](https://user-images.githubusercontent.com/57037245/191825722-0ccb22a7-d9b9-4580-a580-216d718554c9.png)

Inkscape: Tabs are became collapsed. The :hover/:checked tabs have no different background color.
![inkscape](https://user-images.githubusercontent.com/57037245/191828804-e713f223-99cd-4f3b-800b-3430e7ab84ff.png)

### Versions

- OS: Fedora 36
- GNOME Version: 42

### Settings

- [ ] I installed the theme from the tar.xz file.
- [x] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [ ] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
Looks like I have to redo this into app specific styles instead. Keep the current legacy style on most apps except those that have a window class where I know there is little chance of breakage.
