### ISSUE TITLE
Increase titlebar height

### ISSUE THREAD

**Issue by aaronnoyes** [lassekongo83/adw-gtk3#180]
### Issue
Titlebar heights are inconsistent. Is there a way to manually override this, or can a change be added to the theme for consistency? I have had this issue in v3.7 and v4.0.

### Examples
Here is the built-in GNOME terminal beside the settings application, note that the titlebars are the same height.
 
![Screenshot from 2022-10-09 22-19-43](https://user-images.githubusercontent.com/30840033/194795029-4b64adcc-dbee-4f5e-9066-0fda79675e93.png)

Here is kitty terminal using adw-gtk3 beside the GNOME settings, note the titlebar for kitty is quite a bit shorter and does not match.

![Screenshot from 2022-10-09 22-19-50](https://user-images.githubusercontent.com/30840033/194795083-ca26dcad-ac29-44d4-b04e-becc002ac219.png)

I can provide more examples or test other applications if need be.

**Comment by lassekongo83** [comment]
Kitty use a legacy titlebar which are shorter by purpose. It doesn't contain anything more than a title and window control buttons.

**Comment by aaronnoyes** [comment]
@lassekongo83 Do you know if there a way in GNOME to set legacy titlebar heights?

**Comment by lassekongo83** [comment]
Add `.ssd .titlebar { min-height: 46px; }` to `~/.config/gtk-3.0/gtk.css` and relog.

**Comment by aaronnoyes** [comment]
@lassekongo83 that worked, thanks!

**Comment by ronny-rentner** [comment]
I think this should be the default. Consistency and beauty are more important than saving a tiny portion of the screen.
