### ISSUE TITLE
KepassXC doesn't use adw-gtk3

### ISSUE THREAD

**Issue by kittyra** [lassekongo83/adw-gtk3#182]
### Describe the issue
KeePassXC doesn't use adw-gtk3 theme and has bold text in title bar.

### Screenshot(s)
![Screenshot from 2022-10-15 08-04-50](https://user-images.githubusercontent.com/110109711/195972881-ec2603f3-8c57-494e-8270-84194295b0bf.png)

### Versions

- OS and version: Fedora 36
- GNOME Version: 42
- KepassXC version: 2.7.1 Flatpak

### Settings

- [x] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
It's a QT app. You'll have to use the [kvantum theme](https://github.com/GabePoel/KvLibadwaita) and then follow this guide I guess. https://www.reddit.com/r/linux/comments/psit31/flatpak_now_supports_qt_theming_with_kvantum/
