### ISSUE TITLE
Gedit: Very bad contrast of highlighted line (dark)

### ISSUE THREAD

**Issue by jthomaschewski** [lassekongo83/adw-gtk3#184]
When having the option "Hightlight current line" enabled, the text of the current line is unreadable due to bad contrast between text and it's background.
See screenshots.

This is only a problem in the dark theme, light theme looks alright.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/682607/196447637-f8bd4bac-aa36-40c6-82a4-a69786a8f428.png)

adw-gtk3-dark:
![image](https://user-images.githubusercontent.com/682607/196447793-4158fde9-bb5e-4f89-9e62-afe482f21a74.png)

adw-gtk3:
![image](https://user-images.githubusercontent.com/682607/196447929-5c893b89-8f28-470d-ac43-c06d586b3ad1.png)

### Versions

- OS and version: Arch
- GNOME Version: 42 / gedit 42.2
- adw-gtk3: 0.4 (same issue with latest `main` 008fd31)

**Comment by lassekongo83** [comment]
https://gitlab.gnome.org/GNOME/gedit/-/issues/127

Some color schemes for gtksourceview wasn't designed with dark themes in mind, so you'll have to select another one. Nothing can be done in this theme.
