### ISSUE TITLE
Tried to disable rounded corners, but the border is still rounded -- and some applications don't change at all

### ISSUE THREAD

**Issue by Yasand123** [lassekongo83/adw-gtk3#185]
### Describe the issue
I'm trying to disable rounded corners in applications, this works fine for gtk4 applications but for gtk3 (this theme) it seems it's not as simple as adding this to `~/.config/gtk-3.0/gtk.css`
```
window {
	border-bottom-left-radius: 0px;
	border-bottom-right-radius: 0px;
	border-top-left-radius: 0px;
	border-top-right-radius: 0px;
}
```

Some apps have the border issue like Eye of GNOME (window on the right), and other apps aren't affected at all, like GNOME terminal (left in screenshot).

Note that I've restarted the PC, I also don't have anything else in the css file. Only what I wrote here.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/14009700/197315055-67b60e3f-a13d-466e-9637-56454219c9ae.png)

### Versions
- OS and version: Arch 6.0.2
- GNOME Version: 42.4

### Settings
- [ ] I installed the theme from the tar.xz file.
- [x] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
Try:

```css
window, .titlebar, headerbar {
 border-radius: 0;
}
```

**Comment by Yasand123** [comment]
> Try:
> 
> ```css
> window, .titlebar, headerbar {
>  border-radius: 0;
> }
> ```

That fixed one issue where some apps were not affected like GNOME terminal. But the border is still rounded in all gtk3 apps. Tried logging out.

**Comment by lassekongo83** [comment]
Forgot one:

```css
window, .titlebar, headerbar, decoration {
 border-radius: 0;
}
```

**Comment by Yasand123** [comment]
Fixed. Thank you!
