### ISSUE TITLE
VSCode inner toolbar not respecting dark theme

### ISSUE THREAD

**Issue by adhadse** [lassekongo83/adw-gtk3#188]
### Describe the issue
Using adw-gtk3-dark theme from extracted file leads to toolbar section of VSCode with light theme. I am using a `darcula` theme for my editor (if that affects the application)

### Screenshot(s)
![image](https://user-images.githubusercontent.com/56764399/197336391-306ae406-09a3-4087-8b32-d8b297ce023c.png)

Fo reference:
![image](https://user-images.githubusercontent.com/56764399/197336561-d060d84c-b005-43ca-be93-a6057ce226cb.png)

For reference this is what default adwaita-dark does to toolbar:
![image](https://user-images.githubusercontent.com/56764399/197336595-62ea06bb-15a2-4518-98ce-178596d98dcf.png)

### Versions

- OS and version: [e.g Fedora 36] 36
- GNOME Version: [e.g 42] 42
- Flatpak com.visualstudio.code:  1.71.2-1663191218

### Settings

- [X] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [X] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [X] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [X] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
> I've installed the dark flatpak theme: org.gtk.Gtk3theme.adw-gtk3-dark

Try: `flatpak install org.gtk.Gtk3theme.adw-gtk3-dark`

**Comment by adhadse** [comment]
Thanks!!! That resolved the issue. Closing.
