### ISSUE TITLE
Fedora Silverblue install instructions

### ISSUE THREAD

**Issue by dusansimic** [lassekongo83/adw-gtk3#189]
### Describe the issue

Why are instructions for installing on Fedora Silverblue in the README file to put the themes in `~/.themes` directory. If stuff is installed in user directories, Silverblue is no different from regular Fedora. `.local/share/themes` should work everywhere (and it does on Silverblue on my machine) since GNOME has started handling XDG paths.

### Versions

- OS and version: Fedora Silverblue 37 beta
- GNOME Version: 43

### Settings

- [x] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [ ] The theme is the latest available version/git commit.
- [x] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
It was because of https://github.com/lassekongo83/adw-gtk3/issues/101#issuecomment-1163007472

Some things may have changed since then, or some apps may still have the issue. I haven't tested it since.

**Comment by dusansimic** [comment]
Okay, I'll test it out more and see if there are any changes. If everything seems to be working, is it okay to send a pr to fix the docs?

**Comment by lassekongo83** [comment]
I'm about to do some cleaning in the docs, so not necessary to do a pr.
