### ISSUE TITLE
Tabs on GNOME Console (King's Cross) are transparent.

### ISSUE THREAD

**Issue by AbrarSL** [lassekongo83/adw-gtk3#19]
![Screenshot from 2022-02-02 12-13-34](https://user-images.githubusercontent.com/69783006/152106629-cc996182-24da-433a-bd59-f4120e6fa17d.png)
![Screenshot from 2022-02-02 12-13-48](https://user-images.githubusercontent.com/69783006/152106633-e5d5c356-878b-46f2-b5ca-fc5aca351c32.png)
![Screenshot from 2022-02-02 12-14-17](https://user-images.githubusercontent.com/69783006/152106638-559fcc7d-d8bd-4dd8-9930-56e6c50f73c4.png)

**Comment by AbrarSL** [comment]
That was unbelievably fast! Thanks!

**Comment by Vixeliz** [comment]
I'm still encountering this issue with the latest release and with the git version from aur

**Comment by lassekongo83** [comment]
@Vixeliz Try installing it from the extra arch repo. `gnome-console`

Make sure you have `libhandy` installed as well.
