### ISSUE TITLE
There should be some documentation for installing adw-gtk3 from copr for silverblue

### ISSUE THREAD

**Issue by dankmemermusic** [lassekongo83/adw-gtk3#194]
All you gotta do is add the following to the readme file. this would be good if you want to install it for all users.

1. `sudo wget -P /etc/yum.repos.d/ "repo url"`
for the repo url go to https://copr.fedorainfracloud.org/coprs/nickavem/adw-gtk3/ press the download button for the fedora release you are using then copy and paste it where the "repo url" was. remove the quotation marks
example
`sudo wget -P /etc/yum.repos.d/ https://copr.fedorainfracloud.org/coprs/nickavem/adw-gtk3/repo/fedora-37/nickavem-adw-gtk3-fedora-37.repo`

2. then upgade
`sudo rpm-ostree upgrade`

3. then reboot using `systemctl reboot`

4. then install the theme
`sudo rpm-ostree install adw-gtk3`

5. then reboot using `systemctl reboot`

then you should find the themes in gnome tweaks

**Comment by jurf** [comment]
You can actually skip step 2 and 3 and just directly install it.

**Comment by bellegarde-c** [comment]
Another solution I'm using is just linking to flatpak version:
```

[gnumdk@toolbox ~]$ ls -l .local/share/themes/adw-gtk3*
.local/share/themes/adw-gtk3:
total 4
lrwxrwxrwx. 1 gnumdk gnumdk 73 Aug 15 16:23 gtk-3.0 -> ../../flatpak/runtime/org.gtk.Gtk3theme.adw-gtk3/x86_64/3.22/active/files

.local/share/themes/adw-gtk3-dark:
total 4
lrwxrwxrwx. 1 gnumdk gnumdk 78 Aug 15 16:23 gtk-3.0 -> ../../flatpak/runtime/org.gtk.Gtk3theme.adw-gtk3-dark/x86_64/3.22/active/files

```
