### ISSUE TITLE
Gnome Files (Nautilus) error when open right click menu

### ISSUE THREAD

**Issue by chnavarro** [lassekongo83/adw-gtk3#198]
### Nautilus error

Gnome Files (Nautilus) error when opening right-click menu, but works when hovering. when the theme is not applied the menu works fine.

###
[Screencast from 2022-11-25 17-14-25.webm](https://user-images.githubusercontent.com/36161094/204062648-0008ea0f-22c3-416a-b99f-6e3d54542df3.webm)
 Screenshot(s)

### Versions

- OS and version: Fedora 37
- GNOME Version: 43.1
- Files (Nautilus) 34.0

**Comment by lassekongo83** [comment]
Nautilus 43 is using libadwaita.
