### ISSUE TITLE
Highlighted widgets in out-of-focus windows do not have proper color contrast

### ISSUE THREAD

**Issue by rmnscnce** [lassekongo83/adw-gtk3#2]
Operating System: Fedora 35 Workstation x86_64 (with `sassc-3.6.2-3.fc35`)
Git commit: c9b3ed3bba68824a3168bdff75aad4054039fd30

### GNOME Settings
adw-gtk3:
![image](https://user-images.githubusercontent.com/31619874/150440281-0d418a6f-e5be-4d62-8fc8-cff453a98da4.png)
Adwaita:
![image](https://user-images.githubusercontent.com/31619874/150440344-8d50eee0-589f-403a-9e93-af2ed95f64e8.png)
adw-gtk3-dark:
![image](https://user-images.githubusercontent.com/31619874/150440407-269ffab4-2b1b-4bde-92b7-42bfea63e8d6.png)
Adwaita-dark:
![image](https://user-images.githubusercontent.com/31619874/150440440-3723beb9-3713-45b1-b321-754afa49580f.png)

**Comment by rmnscnce** [comment]
Has there been any updates on this issue? If there's been indeed an update, please tell me.

**Comment by lassekongo83** [comment]
Yes, but there are still some widgets that needs to be fixed. (Switches).
