### ISSUE TITLE
Inkscape flatpak not respecting Dark theme

### ISSUE THREAD

**Issue by Hedronmx** [lassekongo83/adw-gtk3#200]
### Describe the issue

Inkscape does not use adw gtk dark, it defaults to standard light theme. I have installed flatpak theme and even added the path on other files using Flatseal.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/26935602/204498589-71054211-4821-480e-b431-932269e89a17.png)

### Versions

- OS and version: Fedora 37
- GNOME Version: 43

Inkscape Flatpak version 1.2.1

### Settings

- [x] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [ ] The theme is the latest available version/git commit.
- [x] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by Hedronmx** [comment]
Removed flatseal settings and i have no env variable set anywhere. And inkscape still on light theme

![image](https://user-images.githubusercontent.com/26935602/204701431-343f9e5b-bb36-48b3-8b4b-f739fe858003.png)

![image](https://user-images.githubusercontent.com/26935602/204701478-f015e482-8813-4a52-8a0e-81462b27d7ff.png)

**Comment by lassekongo83** [comment]
Is the theme installed in `~/.local/share/themes` or `/usr/share/themes`?
