### ISSUE TITLE
White line above title bar

### ISSUE THREAD

**Issue by ksangers** [lassekongo83/adw-gtk3#201]
When I use this theme I get a pixel high white line in the top part of the title bar. 

![image](https://user-images.githubusercontent.com/1464877/205505124-da34545c-bf6c-4c35-b74a-ded087a1b583.png)

### Versions

- OS and version: Arch Linux
- GNOME Version: 43.1

### Settings

- [ ] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [x] I installed the theme from elsewhere. (From AUR)
- [ ] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by emansom** [comment]
GNOME 43 hit the repos a while ago. Positive you are running 42?

**Comment by ksangers** [comment]
Oh dang, you're right. It's 43.1. I'll update it in the description as well

**Comment by lassekongo83** [comment]
Can't reproduce. Any specific app it's happening to?

**Comment by ksangers** [comment]
Any GTK3 app. The screenshot is Signal (`signal-desktop`), but Firefox has the same issue. I reckon it's probably related to my set up then.

Do you happen to have any suggestions for me where to start debugging this?

**Comment by emansom** [comment]
Not observing this issue using [`adw-gtk-theme`](https://aur.archlinux.org/packages/adw-gtk-theme) with GTK theme set to `Adw` and Firefox themed with [`firefox-gnome-theme-git`](https://aur.archlinux.org/packages/firefox-gnome-theme-git).

**Comment by lassekongo83** [comment]
Check `~/.themes` and `~/.local/share/themes` to see if you don't have any older version of the theme lurking anywhere.

**Comment by ksangers** [comment]
I checked it, they were empty. However, I did manage to solve it by fully removing gnome (also from /etc, /var & /usr) and reinstalling it again. Bit overkill maybe, but I figured it was clear something messed up on my end.

Sorry for bothering you and thanks for your assistance!
