### ISSUE TITLE
Removing the inactive button background from the window buttons

### ISSUE THREAD

**Issue by linusrg1** [lassekongo83/adw-gtk3#204]
I applied some custom css to remove the inactive window button background from libadwaita application windows. I am wondering where the code for the inactive window button background is located in adw-gtk3's code because I would like to modify it so adw-gtk3 is consistent with my libadwaita modifications. 

I know this isn't probably something I should of posted, sorry about that. 

Thanks.

**Comment by lassekongo83** [comment]
https://github.com/lassekongo83/adw-gtk3/blob/ac710a7659621c8b41dc63adda05dc6b72d02820/gtk/src/adw-gtk3/gtk-3.0/_common.scss#L4612
https://github.com/lassekongo83/adw-gtk3/blob/ac710a7659621c8b41dc63adda05dc6b72d02820/gtk/src/adw-gtk3/gtk-3.0/_custom.scss#L480
https://github.com/lassekongo83/adw-gtk3/blob/ac710a7659621c8b41dc63adda05dc6b72d02820/gtk/src/adw-gtk3/gtk-3.0/_common.scss#L1687

**Comment by linusrg1** [comment]
Sorry, but I can't quite figure out what I am supposed to do with these lines. I tried changing "$titlebutton_backdrop" to "transparent", as well as just straight up deleting the line, but neither seems to have worked.
