### ISSUE TITLE
Strange artefacts

### ISSUE THREAD

**Issue by DDoubleU** [lassekongo83/adw-gtk3#205]
Hi,

I've followed the instructions and downloaded the tarball from the latest release. I've copied its contents to the proper directory and used gnome-tweaks to select it as my theme for legacy applications. It works, but shows strange artefacts especially on toggles, radiobuttons, checkboxes, ...

sassc is present on my system. Other (GTK3) don't seem to have this issue.
In dconf-editor the formatting is also faulty:

https://postimg.cc/pyjq9pYr

- OS: Arch
- GNOME Version 43
non-Flatpak applications

### Settings

- [x] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [ ] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

Thanks in advance!

Kind regards

**Comment by emansom** [comment]
Possibly left-overs from other themes.

Install the [hybrid theme from the AUR](https://aur.archlinux.org/packages/adw-gtk-theme) and select `Adw` as legacy GTK theme in GNOME Tweaks.

**Comment by lassekongo83** [comment]
Make sure you don't have any older version of the theme in `/usr/share/themes/` or `~/.themes`

**Comment by DDoubleU** [comment]
Thank you! There was indeed an older version present in ~/.themes. I removed it and installed the package through AUR. Everything works fine now.
