### ISSUE TITLE
GTK4 theme inconsistency

### ISSUE THREAD

**Issue by stpnwf** [lassekongo83/adw-gtk3#207]
### Describe the issue

Headbar and card separator, and card divider look different than on GTK4.

### Screenshot(s)

This is what it looks on GTK3 applications

![Screenshot from 2022-12-28 15-28-08](https://user-images.githubusercontent.com/81482539/209843622-4e10790a-a0fe-4c64-a55e-02c0b4327132.png)

This is what it looks on GTK4 applications (themed with Gradience), and what I would expect GTK3 applications to look like.

![Screenshot from 2022-12-28 16-34-17](https://user-images.githubusercontent.com/81482539/209843628-ede217fd-67ae-405a-b4ce-8f73cdfe364c.png)

At first I thought it could be happening because of rgbA incompatibility `rgba(107,138,127,0.0)` , as I was setting the alpha value to zero to hide the header bar separator, and to 0.05 `rgba(107,138,127,0.05)` to hide the card separator. But when I instead tried hiding those by using the same rgb value as the header bar bg color rgb(27,36,33) and card bg color rgb(21,28,25) without an alpha value, the same issue occurred. So I am unsure of what could be causing it.

### Versions

- OS and version: Vanilla OS
- GNOME Version: 43.1

### Settings

- [X] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [X] The theme is the latest available version/git commit.
- [X] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [X] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [X] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [X] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
The headerbar was fixed a while back, so update the theme.

**Comment by stpnwf** [comment]
Oh ok, I was using the latest release to test this. I will try figuring out how to build it from source this weekend. 

BTW I just noticed that in the first screenshot the Titles are White rather than themed like the second screenshot.

**Comment by lassekongo83** [comment]
It is possible that the headerbar_shade_color doesn't support a transparent color.

**Comment by stpnwf** [comment]
>At first I thought it could be happening because of rgbA incompatibility rgba(107,138,127,0.0) , as I was setting the alpha value to zero to hide the header bar, and to 0.05 rgba(107,138,127,0.05) to hide the card separator. But when I instead tried hiding those by using the same rgb value as the header bar bg color rgb(27,36,33) and card bg color rgb(21,28,25) without an alpha value, the same issue occurred. So I am unsure of what could be causing it.

That was the first thing I thought. But when I set them to the same color as the `headerbar_bg_color` and `card_bg_color` respectively, nothing changed. It still looked the **exact** same as the pic. Which would indicate adw-gtk3 is not using the above varibles to render those, or that the thme didn't update after I reapplied it with Gradience, despite me logging out 2-3 times.

**Comment by stpnwf** [comment]
>At first I thought it could be happening because of rgbA incompatibility `rgba(107,138,127,0.0)` , as I was setting the alpha value to zero to hide the header bar separator, and to 0.05 `rgba(107,138,127,0.05)` to hide the card separator. But when I instead tried hiding those by using the same rgb value as the header bar bg color rgb(27,36,33) and card bg color rgb(21,28,25) without an alpha value, the same issue occurred. So I am unsure of what could be causing it.

That was the first thing I thought. But when I set them to the same color as the `headerbar_bg_color` and `card_bg_color` respectively, nothing changed. It still looked the **exact** same as the pic. Which would indicate adw-gtk3 is not using the above varibles to render those, or that the thme didn't update after I reapplied it with Gradience, despite me logging out 2-3 times.

**Comment by lassekongo83** [comment]
So I got around to test it now, and I can't reproduce your issue.

Make sure you don't have any old version of the theme in `/usr/share/themes/` or `~/.themes`

**Comment by stpnwf** [comment]
Ok, thanks. I followed your instructions to build it from source and tested it in a live environment and other than the Titles that remained White rather than themed, everything worked. Thanks for the advice.
