### ISSUE TITLE
Not an issue, just a question re XFCE

### ISSUE THREAD

**Issue by fblais** [lassekongo83/adw-gtk3#210]
Hi.
I didn't know where to ask this, sorry.
I just wanted to ask if you plan to add XFCE decorations to this great theme please?

Thanks in advance, and best regards,
François

**Comment by lassekongo83** [comment]
I'll leave that to someone else.

**Comment by FabianOvrWrt** [comment]
Check this out @fblais https://github.com/FabianOvrWrt/adw-xfwm4

**Comment by fblais** [comment]
Thanks!
I'll check that tonight.

Best!

**Comment by fblais** [comment]
> Check this out @fblais https://github.com/FabianOvrWrt/adw-xfwm4

Works great, thanks!  :)
