### ISSUE TITLE
Doesn't get applied to GNOME Web

### ISSUE THREAD

**Issue by PhilDevProg** [lassekongo83/adw-gtk3#216]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

I installed everything according to the README but GNOME Web doesn't pick up the theme. Every other Flatpak app does...

### OS and version [e.g Fedora 37]

Fedora 37

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

3.22, Flatpak

### GNOME version

43.2

### Application name and version (If the issue is with an app.)

GNOME Web (43.0)

**Comment by lassekongo83** [comment]
Did you install the flatpak theme or gnome web as root? Preferably it should be installed as a user.

**Comment by PhilDevProg** [comment]
Seems to be an issue of the Flatpak provided by the Fedora Flatpak repo. I installed Web with Flathub and it worked.

**Comment by lorhof1** [comment]
I have also noticed that fedora flatpaks do not seem to work. Maybe this should be added the readme or something like this, as the fix (installing the flathub ones instead) was not very obvious to me.
