### ISSUE TITLE
Dark theme doesn't get applied to transmission 4.0

### ISSUE THREAD

**Issue by bbhtt** [lassekongo83/adw-gtk3#218]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

The dark theme doesn't get applied to the newest transmission version 4.0.1 previously with 3.0.0 I think it was working fine.

Screenrecord:

[Screencast from 2023-03-03 13-52-36.webm](https://user-images.githubusercontent.com/62639087/222669399-7605702d-00a5-4793-b33f-80edef748068.webm)

Theme and transmission are both from Arch repositories.

### OS and version [e.g Fedora 37]

Arch Linux

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

4.3.r2.d2bb032-1

### GNOME version

44 beta

### Application name and version (If the issue is with an app.)

Transmission 4.0.1

**Comment by bbhtt** [comment]
Ah, I think the issue is 4.0 is ported to GTK4 and doesn't have its own dark mode https://github.com/transmission/transmission/releases/tag/4.0.0-beta.2 (I missed it because this is mentioned in the beta tag only not in the changelog of 4.0)

**Comment by lassekongo83** [comment]
Does this work? https://github.com/lassekongo83/adw-gtk3/blob/main/gtk4.md

**Comment by bbhtt** [comment]
I need to try that but as a workaround I haveset the GTK_THEME=Adwaita:dark environment variable for transmission only.

Closing since this is not an issue with this theme.

**Comment by bbhtt** [comment]
> Does this work? https://aur.archlinux.org/packages/adw-gtk-theme (or https://github.com/lassekongo83/adw-gtk3/blob/main/gtk4.md)

Seems to be working well mostly

![image](https://user-images.githubusercontent.com/62639087/222878307-f229d11d-83be-4dc4-8e95-0f25143469b5.png)
