### ISSUE TITLE
Titlebar of apps uses adwaita-dark titlebar in both light and dark mode since Gnome 44

### ISSUE THREAD

**Issue by sith-on-mars** [lassekongo83/adw-gtk3#219]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

Apps that use traditional titlebars show the adwaita-dark titlebar in both light and dark mode. It seems for some reasons, GTK3 apps are forced to use legacy adwaita-dark titlebar. Adw-gtk3 work fine in the rest part of the app. It appears that the issue is affecting both Flatpak and non-Flatpak apps.

The issue only occurred since updating to Gnome 44. There is no such problem on apps that use CSD. No problem on apps using traditional packaging.

The screenshot when using Adw-gtk3-dark in Flatpak version of Zotero which uses traditional titlebar:

![image](https://user-images.githubusercontent.com/37974764/227781640-a7418060-31df-4e5d-8782-0ebc0ccce4d4.png)

The screenshot when using Adw-gtk3 in Flatpak version of Zotero which uses traditional titlebar:

![image](https://user-images.githubusercontent.com/37974764/227781728-00967523-acfb-45dd-bb1c-1a253a53899f.png)

### OS and version [e.g Fedora 37]

OpenSUSE MicroOS

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

4.4

### GNOME version

44

**Comment by vrmaurice** [comment]
I'm having the same issue on Fedora 38 Beta. It not only happens on Flatpak apps. I installed VS Code as an rpm and it happens on Code too.

**Comment by lassekongo83** [comment]
Is the issue the same between xorg and wayland? Unable to test at the moment.

**Comment by vrmaurice** [comment]
Yes it is

**Comment by beganovich** [comment]
I believe this is an issue with latest changes to Mutter, dropping support for GTK3. 

https://www.phoronix.com/news/GNOME-Shell-Mutter-No-GTK3

**Comment by lassekongo83** [comment]
Is there any change if you add: (You may have to relog to see any change.)

```css
.ssd .titlebar, .ssd { background: pink; }
```

to `~/.config/gtk-4.0/gtk.css`

Flatpak apps will need to be able to read that as well: `sudo flatpak override --filesystem=xdg-config/gtk-4.0`

**Comment by vrmaurice** [comment]
I didn't even had `gtk.css` in that folder. I just created it, pasted the file in it, logged back in. No change at all.

I don't know if this is relevant or not, but it only seems to be happening with XWayland windows.
I also want to add that the titlebar doesn't always use the `adwaita-dark` one, it does follow the dark and light modes. It just seems like the theme isn't applied.

**Comment by thomasreader** [comment]
> Is there any change if you add: (You may have to relog to see any change.)
> 
> ```css
> .ssd .titlebar, .ssd { background: pink; }
> ```
> 
> to `~/.config/gtk-4.0/gtk.css`
> 
> Flatpak apps will need to be able to read that as well: `sudo flatpak override --filesystem=xdg-config/gtk-4.0`

Didn't seem to do anything for me after re-logging and restarting.

With default rather than dark mode all of the Stilo and Zuki themes work: 

![Screenshot from 2023-03-30 12-52-22](https://user-images.githubusercontent.com/29782928/228830206-14ff88ab-08a9-46eb-a639-cdeb625d8849.png)

![Screenshot from 2023-03-30 12-52-29](https://user-images.githubusercontent.com/29782928/228829882-d0a3dd45-cce5-4263-84c8-a5ff43ed65f4.png)

![Screenshot from 2023-03-30 12-52-50](https://user-images.githubusercontent.com/29782928/228829960-66da5feb-c49a-4c87-a166-5d1fa0e99c32.png)

Out of nowhere Firefox seems to be picking up the theme: nothing has been updated but I did cycle through various themes, switching between light and dark mode and enabling / disabling the menu bar in Firefox — which is a bit strange!

![Screenshot from 2023-03-30 13-00-15](https://user-images.githubusercontent.com/29782928/228830055-653a4fdb-d243-483d-8eeb-c35585b6d9d3.png)

**Comment by lassekongo83** [comment]
@thomasreader Where are the themes installed?

**Comment by thomasreader** [comment]
> @thomasreader Where are the themes installed?

All are in /usr/share/themes

**Comment by thomasreader** [comment]
I don't know if its of any help but I did a bit of random linking with the gtk-x.0 folders to different themes. Providing the dummy theme had a link to the gtk-4.0 folder in Zukitwo or Stilo etc. the title bars updated. 

At one point i had 

- gtk-2.0 -> Adwaita
- gtk-3.0 adw-gtk3
- gtk-4.0 Zukitwo 

and the title bars still updated styled as Zukitwo — albeit the assets for the buttons weren't there.

**Comment by lassekongo83** [comment]
I guess that confirms that legacy titlebars are now styled with gtk4. Does this fix this issue? https://github.com/lassekongo83/adw-gtk3/blob/main/gtk4.md

**Comment by thomasreader** [comment]
> I guess that confirms that legacy titlebars are now styled with gtk4. Does this fix this issue? https://github.com/lassekongo83/adw-gtk3/blob/main/gtk4.md

That has fixed it it for Default Mode, can pick adw-gtk3 or dark, but for some reason when Dark Mode is enabled it doesn't work.

**Comment by lassekongo83** [comment]
You need to manually add `@import 'defaults-dark.css';` instead of `defaults-light.css`to the gtk.css file. Then the dark theme should work.

**Comment by sith-on-mars** [comment]
Anybody else has issue building adw-gtk3 for gtk4 apps? I'm using Arch distrobox and encounter the following issue. Using Fedora distrobox generated a similar result.

```
[dadstick@arch-distrobox ~]$ git clone https://gitlab.gnome.org/GNOME/libadwaita.git
cd libadwaita
Cloning into 'libadwaita'...
remote: Enumerating objects: 29116, done.
remote: Counting objects: 100% (2533/2533), done.
remote: Compressing objects: 100% (462/462), done.
remote: Total 29116 (delta 2185), reused 2348 (delta 2070), pack-reused 26583
Receiving objects: 100% (29116/29116), 14.15 MiB | 2.56 MiB/s, done.
Resolving deltas: 100% (22957/22957), done.
[dadstick@arch-distrobox libadwaita]$ meson . _build
The Meson build system
Version: 1.0.1
Source dir: /home/dadstick/libadwaita
Build dir: /home/dadstick/libadwaita/_build
Build type: native build
Project name: libadwaita
Project version: 1.4.alpha
C compiler for the host machine: cc (gcc 12.2.1 "cc (GCC) 12.2.1 20230201")
C linker for the host machine: cc ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wdate-time: YES 
Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -Werror=missing-declarations: YES 
Compiler for C supports arguments -Werror=overflow: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=shift-count-overflow: YES 
Compiler for C supports arguments -Werror=shift-overflow=2: YES 
Compiler for C supports arguments -Werror=implicit-fallthrough=3: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wmaybe-uninitialized: YES 
Compiler for C supports arguments -Wmissing-field-initializers: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wmissing-noreturn: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-sign-compare: YES 
Compiler for C supports arguments -Wno-strict-aliasing: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wredundant-decls: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wswitch-default: YES 
Compiler for C supports arguments -Wswitch-enum: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wunused-function: YES 
Compiler for C supports arguments -Wfloat-equal: YES 
Compiler for C supports arguments -fstack-protector-strong: YES 
Program sassc found: YES (/usr/sbin/sassc)
Found pkg-config: /usr/sbin/pkg-config (1.8.1)
Program glib-compile-resources found: YES (/usr/sbin/glib-compile-resources)
Program glib-compile-resources found: YES (/usr/sbin/glib-compile-resources)
Configuring adw-version.h using configuration
Program glib-mkenums found: YES (/usr/sbin/glib-mkenums)
Program glib-mkenums found: YES (/usr/sbin/glib-mkenums)
Program glib-mkenums found: YES (/usr/sbin/glib-mkenums)
Program glib-mkenums found: YES (/usr/sbin/glib-mkenums)
Program glib-genmarshal found: YES (/usr/sbin/glib-genmarshal)
Program gen-public-types.py found: YES (/usr/bin/python /home/dadstick/libadwaita/src/gen-public-types.py)
Found pkg-config: /usr/sbin/pkg-config (1.8.1)
Run-time dependency gio-2.0 found: YES 2.76.1
Run-time dependency gtk4 found: YES 4.10.1
Found CMake: /usr/sbin/cmake (3.26.2)
Run-time dependency appstream found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency appstream
Cloning into 'appstream'...
remote: Enumerating objects: 555, done.
remote: Counting objects: 100% (555/555), done.
remote: Compressing objects: 100% (469/469), done.
remote: Total 555 (delta 146), reused 242 (delta 55), pack-reused 0
Receiving objects: 100% (555/555), 2.99 MiB | 9.06 MiB/s, done.
Resolving deltas: 100% (146/146), done.

Executing subproject appstream 

appstream| Project name: AppStream
appstream| Project version: 0.16.2
appstream| C compiler for the host machine: cc (gcc 12.2.1 "cc (GCC) 12.2.1 20230201")
appstream| C linker for the host machine: cc ld.bfd 2.40
appstream| Configuring config.h using configuration
appstream| Compiler for C supports arguments -Werror=shadow: YES
appstream| Compiler for C supports arguments -Werror=empty-body: YES
appstream| Compiler for C supports arguments -Werror=strict-prototypes: YES
appstream| Compiler for C supports arguments -Werror=missing-prototypes: YES
appstream| Compiler for C supports arguments -Werror=implicit-function-declaration: YES
appstream| Compiler for C supports arguments -Werror=pointer-arith: YES
appstream| Compiler for C supports arguments -Werror=missing-declarations: YES (cached)
appstream| Compiler for C supports arguments -Werror=return-type: YES (cached)
appstream| Compiler for C supports arguments -Werror=int-conversion: YES
appstream| Compiler for C supports arguments -Werror=incompatible-pointer-types: YES (cached)
appstream| Compiler for C supports arguments -Werror=misleading-indentation: YES
appstream| Compiler for C supports arguments -Werror=missing-include-dirs: YES
appstream| Compiler for C supports arguments -Werror=declaration-after-statement: YES
appstream| Compiler for C supports arguments -Werror=format-security: NO
appstream| Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
appstream| Compiler for C supports arguments -Wno-error=missing-field-initializers: YES
appstream| Compiler for C supports arguments -Wno-unused-parameter: YES (cached)
appstream| Compiler for C supports arguments -Wno-error=unused-parameter: YES
appstream| Run-time dependency glib-2.0 found: YES 2.76.1
appstream| Run-time dependency gobject-2.0 found: YES 2.76.1
appstream| Dependency gio-2.0 found: YES 2.76.1 (cached)
appstream| Run-time dependency gio-unix-2.0 found: YES 2.76.1
appstream| Run-time dependency libcurl found: YES 8.0.1
appstream| Run-time dependency libxml-2.0 found: YES 2.10.3
appstream| Run-time dependency yaml-0.1 found: NO (tried pkgconfig and cmake)

subprojects/appstream/meson.build:165:0: ERROR: Dependency "yaml-0.1" not found, tried pkgconfig and cmake

A full log can be found at /home/dadstick/libadwaita/_build/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
[dadstick@arch-distrobox libadwaita]$ ninja -C _build
ninja: Entering directory `_build'
ninja: error: loading 'build.ninja': No such file or directory
```

**Comment by vrmaurice** [comment]
Yup, I'm having the same error messages. I guess we are missing some packages but I can't seem them.

**Comment by thomasreader** [comment]
> You need to manually add `@import 'defaults-dark.css';` instead of `defaults-light.css` to the gtk.css file. Then the dark theme should work.

Both light and dark themes work provided the settings app is set to Default. When it is set to Dark then neither light or dark apply to the problematic apps
[Screencast from 2023-04-01 21-27-48.webm](https://user-images.githubusercontent.com/29782928/229312620-8d90af2d-1878-4eb6-a861-0885d21eed64.webm)

**Comment by lassekongo83** [comment]
If you use the light theme there's no gtk-dark.css file in the gtk4 theme as there is in the gtk3 theme. Try running the following: (and make sure you have the gtk4 theme installed in `adw-gtk3-dark`.

 ```
gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark' && gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'`
```

**Comment by thomasreader** [comment]
Changing the gsettings didn't do anything but creating the `gtk-dark.css` files in both themes worked!

Thank you for your help!

**Comment by thomasreader** [comment]
@sith-on-mars @vrmaurice if you want the .css files I created I have attached them here
[gtk-4.0.tar.gz](https://github.com/lassekongo83/adw-gtk3/files/11132314/gtk-4.0.tar.gz)

**Comment by sith-on-mars** [comment]
The workaround works for me. Thank you @thomasreader and @lassekongo83.

I hope in the future the adw-gtk3 would contain gtk4 theme by default, as more users would upgrade to Gnome 44 in the future.

**Comment by lassekongo83** [comment]
A copy of libadwaita 1.3 base.css file is now included. If you're building the theme from source make sure to remove or reconfigure the build directory.

**Comment by Racsuu** [comment]
hi, this fix  everything for me but only on wayland, on xorg a lot of titlebars still using the other theme and not adw-gtk3 or the gtk4 one, any idea of what i can do?
