### ISSUE TITLE
The 'Close Document' button on the LibreOffice menubar looks bad with the latest version of the theme

### ISSUE THREAD

**Issue by zoli111** [lassekongo83/adw-gtk3#221]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [ ] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

The menubars had the same colors as the window background prior to the latest version of the theme. Now they have different colors, which makes LO to look like this:
![llight](https://user-images.githubusercontent.com/57037245/229375305-9e5e05bc-ba4b-42a7-862b-ce50bf3896a5.png)
![dark](https://user-images.githubusercontent.com/57037245/229375330-9c1386b2-930b-424d-accc-57472648ca21.png)

Inserting this piece of CSS code into the GTK debug window made it look right.
![css](https://user-images.githubusercontent.com/57037245/229376663-82412f26-648e-483d-b0a1-259d39b3fb22.png)

Unfortunately I didn't find any LO-specific CSS selectors, so I'm not sure if this can be safely fixed in the theme.

### OS and version [e.g Fedora 37]

Arch

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

4.4

### Application name and version (If the issue is with an app.)

Libreoffice 7.5.2

**Comment by lassekongo83** [comment]
This has already been fixed in the main branch.
