### ISSUE TITLE
adw-gtk3 in fedora repos

### ISSUE THREAD

**Issue by solopasha** [lassekongo83/adw-gtk3#224]
Hi! Thanks a ton for your great theme! FYI, I've packaged it in fedora: https://src.fedoraproject.org/rpms/adw-gtk3-theme, it'll hit stable repos soon:
https://bodhi.fedoraproject.org/updates/FEDORA-2023-8c18494491

**Comment by REALERvolker1** [comment]
I was pretty surprised to find this theme in the Fedora 38 repos. This clears things up. Thanks for packaging it, I guess I don't have to keep updating it from git now 😅
