### ISSUE TITLE
4.6 introduced bare visible selection in Chrome in dark

### ISSUE THREAD

**Issue by darkblaze69** [lassekongo83/adw-gtk3#227]
Arch Linux, GNOME 44.1
4.6 introduced bare visible selection at least in Chrome in dark:

4.6 (bad behavior):
![Screenshot from 2023-05-10 10-24-38](https://github.com/lassekongo83/adw-gtk3/assets/6976920/bdf87a7a-8f3f-41e9-9186-f6f1b91fc4e5)
![Screenshot from 2023-05-10 10-24-52](https://github.com/lassekongo83/adw-gtk3/assets/6976920/f6967685-d8fc-4dfb-8c06-5e28459c8041)

4.5 (good):
![Screenshot from 2023-05-10 10-22-51](https://github.com/lassekongo83/adw-gtk3/assets/6976920/586fae1e-f6b3-4b9b-b3c8-0c0debfc7efc)
![Screenshot from 2023-05-10 10-23-06](https://github.com/lassekongo83/adw-gtk3/assets/6976920/0c04ecd6-9463-476c-9702-c3d6b106361c)

**Comment by lassekongo83** [comment]
Fixed in main branch. https://github.com/lassekongo83/adw-gtk3/commit/c30193334319a616392ef18985217f8499b1754d

**Comment by darkblaze69** [comment]
Other apps are also affected like Remmina and virt-manager.

4.5:
![Screenshot from 2023-05-16 23-36-44](https://github.com/lassekongo83/adw-gtk3/assets/6976920/6fe5d257-2969-4295-bf21-38b00fcdc738)

4.6:
![Screenshot from 2023-05-16 23-39-36](https://github.com/lassekongo83/adw-gtk3/assets/6976920/185b845e-28b5-422b-897c-d7c402ddf76e)

**Comment by lassekongo83** [comment]
Yeah, that's intentional. It's the default selection color in libadwaita.
