### ISSUE TITLE
GTK4 Theme?

### ISSUE THREAD

**Issue by korewaChino** [lassekongo83/adw-gtk3#23]
I know this may be out of scope, but are you going to port this to a standard GTK4 stylesheet? So non-libadwaita GTK4 apps are also able to utilize this theme too.

**Comment by SilverMarcs** [comment]
Most, if not all gtk4 apps would switch to libadwaita anyway. the extensions app for example already uses libadwaita in gnome 42. Safe to assume celluloid and others would follow.

**Comment by korewaChino** [comment]
Might as well make it for all the other apps that would not use libadwaita. In case people actually start making standard GTK4 apps that do not use libadwaita (for certain reasons) would have a consistent look with the other libadwaita apps.

**Comment by lassekongo83** [comment]
Currently no plans. I'll wait and see.

**Comment by SilverMarcs** [comment]
> Might as well make it for all the other apps that would not use libadwaita. In case people actually start making standard GTK4 apps that do not use libadwaita (for certain reasons) would have a consistent look with the other libadwaita apps.

I doubt gtk4 gnome apps wont adapt to libadwaita but I suppose gtk4 would be used by non-gnome apps as well, and so you have a point.

**Comment by diego-sergio** [comment]
No need to make a new stylesheet, just use the standard libadwaita.
Here is the latest build: [gtk4-libadwaita.zip](https://github.com/lassekongo83/adw-gtk3/files/8009501/gtk4-libadwaita.zip)
Copy the gtk-4.0 folder to the corresponding theme folder.
![Screenshot](https://user-images.githubusercontent.com/25941156/152669308-61c85173-07f6-4690-9757-bf6d1bf0d1b7.png)

**Comment by korewaChino** [comment]
How did you build that stylesheet? I tried building libadwaita myself and it didnt seem to build it for me.

**Comment by Aleksanaa** [comment]
> 

But how did you make this build?

**Comment by diego-pvlk** [comment]
https://gitlab.gnome.org/GNOME/libadwaita

You need all the dependencies installed. On fedora these are the packages:

`
sudo dnf install vala gobject-introspection-devel sassc meson gtk4-devel cmake
`

Fedora 35 doesn't have the `gtk4-devel` needed, I used 36.

To build:
```
meson . _build
ninja -C _build
```
Css files are in /libadwaita/_build/src/stylesheet/

**Comment by jacksongoode** [comment]
My extensions versions is 41 and doesn't play nice with this theme (makes it all white when tweaks is set to dark) do I have to install extensions form the nightly gnome flatpak or just wait?

**Comment by diego-pvlk** [comment]
> My extensions versions is 41 and doesn't play nice with this theme (makes it all white when tweaks is set to dark) do I have to install extensions form the nightly gnome flatpak or just wait?

No idea, when I was using v41 the theme worked fine with the app. Is the theme even changing? If not, you may need to give permission to access the themes folder: `flatpak override --filesystem=~/.themes`

It is updated to 42 on flathub though, you don't need gnome nightly for that.
