### ISSUE TITLE
Tabs are transparent in neovim-gtk

### ISSUE THREAD

**Issue by michael-ball** [lassekongo83/adw-gtk3#232]
Tabs in neovim-gtk (https://github.com/Lyude/neovim-gtk) are transparent when using both adw-gtk3 and adw-gtk3-dark.

Here's a screenshot of the issue using adw-gtk3:

![screenshot_1](https://github.com/lassekongo83/adw-gtk3/assets/4253793/7f9931d5-ab68-4c6c-809c-6d47aa56cb35)

This is how it looks using default Adwaita theme:

![screenshot_2](https://github.com/lassekongo83/adw-gtk3/assets/4253793/a895cf70-e2d5-416d-b23e-e058e24d8317)

**Comment by lassekongo83** [comment]
Is the issue fixed if you remove the gtk-4.0 folder from the theme?

**Comment by michael-ball** [comment]
> Is the issue fixed if you remove the gtk-4.0 folder from the theme?

Yes, removing the gtk-4.0 folder fixes it.
