### ISSUE TITLE
Error: While pulling runtime/org.gtk.Gtk3theme.adw-gtk3-dark/x86_64/3.22 from remote flathub: Input buffer too small error: Failed to install org.gtk.Gtk3theme.adw-gtk3-dark: While pulling runtime/org.gtk.Gtk3theme.adw-gtk3-dark/x86_64/3.22 from remote flathub: Input buffer too small

### ISSUE THREAD

**Issue by hrqmonteiro** [lassekongo83/adw-gtk3#233]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

Error: While pulling runtime/org.gtk.Gtk3theme.adw-gtk3-dark/x86_64/3.22 from remote flathub: Input buffer too small
error: Failed to install org.gtk.Gtk3theme.adw-gtk3-dark: While pulling runtime/org.gtk.Gtk3theme.adw-gtk3-dark/x86_64/3.22 from remote flathub: Input buffer too small

### OS and version [e.g Fedora 37]

Fedora 38

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

latest

### GNOME version

44

**Comment by lassekongo83** [comment]
https://github.com/flatpak/flatpak/issues/5452

**Comment by hrqmonteiro** [comment]
> [flatpak/flatpak#5452](https://github.com/flatpak/flatpak/issues/5452)

Still getting the error even with the "fix" they provided.

**Comment by nicklatch** [comment]
https://github.com/ostreedev/ostree/issues/2900 it's related to this issue in ostree. They are actively triaging it now

**Comment by nicklatch** [comment]
It's related to this issue. They are working on it now. 

https://github.com/ostreedev/ostree/issues/2900
