### ISSUE TITLE
Destructive button has transparent background

### ISSUE THREAD

**Issue by gregorydk** [lassekongo83/adw-gtk3#24]
In Adwaita a destructive button is a button with a red background colour and a white text colour, in adw-gtk3 that button has a transparent background colour and a white text colour making the text unreadable.

**Comment by lassekongo83** [comment]
Works for me.

![buttons](https://user-images.githubusercontent.com/7415624/152642025-93c3e264-b34b-4dae-9495-696a677a89ad.png)

**Comment by gregorydk** [comment]
Maybe I should have specified it happens for me in the app File Roller when you want to delete a file inside an archive.

**Comment by gregorydk** [comment]
Thanks, it looks like it's solved. That was quick. :+1:
