### ISSUE TITLE
Geary sidebar has the wrong color in v4.9

### ISSUE THREAD

**Issue by inthreedee** [lassekongo83/adw-gtk3#240]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

With adw-gtk3 v4.9, Geary's sidebar does not use the correct background color for my theme. Downgrading to 4.8 and restarting Geary fixes the issue.

I am using Gradience v0.4.1 to apply the Catppuccin Mocha Lavender theme.

v4.8 with the correct theme colors:
![Screenshot from 2023-09-09 15-54-05](https://github.com/lassekongo83/adw-gtk3/assets/54287723/e6cb4dc3-a437-403b-a53a-a694f14bbab9)

v4.9 with the incorrect, default Adwaita background color in the sidebar:
![Screenshot from 2023-09-09 15-55-11](https://github.com/lassekongo83/adw-gtk3/assets/54287723/5eedd486-3ad1-43f8-95ea-f3de9faebb1f)

### OS and version [e.g Fedora 37]

Arch

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

4.9/git installed from AUR

### GNOME version

44.4

### Application name and version (If the issue is with an app.)

Geary v44.1, Gradience v0.4.1

**Comment by lassekongo83** [comment]
The value for sidebars are now `sidebar_bg_color`. So add `@define-color sidebar_bg_color your_color;` to `~/.config/gtk-3.0/gtk.css` or wait for a Gradience update to include support for that.

There's also `sidebar_fg_color`, `sidebar_backdrop_color`, and `sidebar_shade_color`.

**Comment by inthreedee** [comment]
@lassekongo83  I'll pass that info along to the Gradience team. Thank you very much!
