### ISSUE TITLE
Geary sidebar looks broken

### ISSUE THREAD

**Issue by kk-mofux** [lassekongo83/adw-gtk3#241]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

The Sidebar in Geary is very dark now compared to older versions. Also there is a status area at the bottom of it not matching the background of the sidebar which makes it look broken.

![geary-sidebar](https://github.com/lassekongo83/adw-gtk3/assets/7723079/412c2112-50ed-40b8-ac6b-5557660046a1)

### OS and version [e.g Fedora 37]

Arch Linux

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

4.9-1

### GNOME version

44.4

### Application name and version (If the issue is with an app.)

Geary 44.1

**Comment by lassekongo83** [comment]
Sidebars are now using the same colors as libadwaita 1.4. You can change it if you want. Open `~/.config/gtk-3.0/gtk.css` and add `@define-color sidebar_bg_color @window_bg_color` and relog/killall geary. As for the bottom area, that may be because of Geary not expanding the sidebar all the way. But it is hard to know as I don't know how to use Geary without an email account.

**Comment by julianfairfax** [comment]
> As for the bottom area, that may be because of Geary not expanding the sidebar all the way. But it is hard to know as I don't know how to use Geary without an email account.

I tried to open the GTK inspector in Geary, but neither `Control` + `Shift` + `I` nor `Control` + `Shift` + `D` work. It must be possible though, and then the issue can be figured out.

**Comment by lassekongo83** [comment]
Did you set the key bind? `gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true`

**Comment by julianfairfax** [comment]
Alright, after doing that it worked.

I'm not sure if this helps, but this is the general structure we're dealing with.

[Screencast from 2023-09-16 09-07-19.webm](https://github.com/lassekongo83/adw-gtk3/assets/43753131/71b5df74-821d-49bb-b961-1ad69544ee0e)

**Comment by lassekongo83** [comment]
Does anything happen if you add `.geary-folder + statusbar { background-color: pink; }` to `~/.config/gtk-3.0/gtk.css`?
(Note that the app need to be completely restarted for the changes to take effect: `killall geary`)

**Comment by julianfairfax** [comment]
Yes, but it only affects the second element in the video, which is not the full statusbar. You will need to apply the changes to the folder-box element above it (I don't know its CSS class). The scrolled window (with the mailboxes) should retain its current colour as it on top of the folder-box.

**Comment by julianfairfax** [comment]
Version 5.0 (from Flathub) did not fix this for me. I logged out and logged back in. Still looks broken.

**Comment by julianfairfax** [comment]
@lassekongo83 the code you had me try was for `.geary-folder + statusbar`, whereas [your code](https://github.com/lassekongo83/adw-gtk3/commit/23eb09ef7d392fd149562d23fb9b7235c116e3f8) is for `.geary-folder`. Could this be the issue?

**Comment by lassekongo83** [comment]
Know of any free and quick test mail (without phone number check) I can use to access the full interface? It's kind of hard to test anything now.

**Comment by przmkg** [comment]
@lassekongo83 I can create a testing account on my domain where you'll be able to use imap & smtp. I'll send you a private message on Lemmy.

**Comment by lassekongo83** [comment]
@przmkg Thanks.

For this app it was possible to mimic the new libadwaita 1.4 style.

**Comment by kk-mofux** [comment]
@lassekongo83 Thanks for your continued efforts! Will test when it's available in a release.

**Comment by julianfairfax** [comment]
Any chance for a hotfix release? This was supposed to have already been fixed, and I don't really want to wait another month or two to get it :(

**Comment by kk-mofux** [comment]
Just got the update, it looks great!
