### ISSUE TITLE
[Question]Sharp corners on ungoogled chromium

### ISSUE THREAD

**Issue by Radical4ever** [lassekongo83/adw-gtk3#242]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

Hi, so this is more like a question/request all of chrome browsers have sharp corners on the context menus when i enable the gtk theme (in this case it applies adw-gtk3) but the corners are not rounded when i use their own theme, but it doesnt look that consistent
![Captura desde 2023-09-18 16-38-51](https://github.com/lassekongo83/adw-gtk3/assets/83252104/ce8d2dfc-1ded-4353-b595-56d456821657)
![image](https://github.com/lassekongo83/adw-gtk3/assets/83252104/43d8d748-6e0b-4fc0-a107-8e8441c4e6f3)

i'm thinking if i need to add a variable to the gtk.css on the theme to round these corners app. if that's possible how can i?. thank you

### OS and version [e.g Fedora 37]

38

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

git

### GNOME version

44

### Application name and version (If the issue is with an app.)

ungoogled chromium (any chrome base app i think this issue can relate)

**Comment by lassekongo83** [comment]
It's not possible to change the border radius on chromium menus.

**Comment by Radical4ever** [comment]
> It's not possible to change the border radius on chromium menus.

Crap, welp, thank anywsws for answering👍
