### ISSUE TITLE
Update Design to follow new Libadwaita 

### ISSUE THREAD

**Issue by mbeps** [lassekongo83/adw-gtk3#243]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

The new Libadwaita has a new design for the sidebar. The sidebar and the rest off the app container are separate. The theme needs to e updated to follow the new Libadwaita design. 

**New design**
![image](https://github.com/lassekongo83/adw-gtk3/assets/58662575/5f6c9ea9-8de9-4ecf-b934-835f10c94ebf)

### OS and version [e.g Fedora 37]

Fedora 39

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

4.9 from Fedora Copr 

### GNOME version

45

**Comment by lassekongo83** [comment]
The sidebar can't be expanded into the headerbar on GTK3. Other than that I've already started some minor work that probably will be finished sometime after Arch gets GNOME 45.
