### ISSUE TITLE
Change corner radius with css

### ISSUE THREAD

**Issue by Odizinne** [lassekongo83/adw-gtk3#244]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

Hello, i'm working on a little project and i would need to reduce the default corner radius for this.

Is this something achievable with css? I tried somes, but it look weird. The gnome ext rounded-window-corners give the same weird result.
```
.background.csd {
    border-radius: 5px 5px 0 0;
}
```
Border radius set to 5px in GTK4 app

![Screenshot from 2023-09-29 17-23-49](https://github.com/lassekongo83/adw-gtk3/assets/102679854/d2dad32f-5450-46e5-bdd0-68718051651d)

Border radius set to 5px in GTK3 app with adw-gtk3

![Screenshot from 2023-09-29 17-24-05](https://github.com/lassekongo83/adw-gtk3/assets/102679854/6637be8f-7b62-49c0-9544-9d70db2a111e)

I think it might be a mutter issue, if i understand the window manager render GTK3 window decorations, but i'm lacking knowledge, so i prefer asking.

### OS and version [e.g Fedora 37]

Arch

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

AUR git

### GNOME version

44

### Application name and version (If the issue is with an app.)

Any GTK3 apps

**Comment by lassekongo83** [comment]
In GTK3 the border radius is handled here: https://github.com/lassekongo83/adw-gtk3/blob/main/gtk/src/adw-gtk3/gtk-3.0/_common.scss#L1771 to line 1804. And also here: https://github.com/lassekongo83/adw-gtk3/blob/main/gtk/src/adw-gtk3/gtk-3.0/_common.scss#L4484
