### ISSUE TITLE
File chooser sidebar bg color

### ISSUE THREAD

**Issue by MOIS3Y** [lassekongo83/adw-gtk3#246]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

It seems to me that adw-gtk3 does not set the background color in the File chooser sidebar.
I checked in different applications, mostly it was transmission-gtk 3.00, but even in awf-gtk3 it is just as noticeable.
I tried installing adw-gtk3 from nixpkgs and adw-gtk3 releases. But this does not affect the problem.
Also, the result is not affected by gtk-application-prefer-dark-theme=true

This is not very noticeable if you use adw-gtk3 without customizing colors.
But if you try color tweaks, it doesn’t matter whether it’s gradience or adw-colors, you will see that the icon color fg but not bg will change.

This is the standard adw-gtk3:
![2023-11-27_14-47](https://github.com/lassekongo83/adw-gtk3/assets/48302224/3f2b5ba8-5585-4d99-bd42-e6ea0b1f4f20)

This is the standard adw-gtk3-dark:
![2023-11-27_14-03](https://github.com/lassekongo83/adw-gtk3/assets/48302224/17b7b6f3-3164-4ef3-86b5-2632d22fe186)

Let's try the tweak using the example of solarizrd dark from adw-colors or nord for dark mode.
![2023-11-27_14-53](https://github.com/lassekongo83/adw-gtk3/assets/48302224/3dfd657a-309e-45ee-a46f-534abfdf73bd)
![2023-11-27_15-00](https://github.com/lassekongo83/adw-gtk3/assets/48302224/03a61cae-d168-4003-b2ea-0126e3c6eadc)

At first I thought that the problem was due to the OS and the fact that I was just using the awesomewm window manager
Therefore, I installed VoidLinux with Gnome 44 on a virtual machine because I had previously used this OS with adw-gtk3 and I don’t remember this problem being there.
But to my surprise I found her there
![2023-11-23_19-52](https://github.com/lassekongo83/adw-gtk3/assets/48302224/bb6c5524-6e4b-4133-9142-74636532369f)
![2023-11-23_19-48](https://github.com/lassekongo83/adw-gtk3/assets/48302224/19172720-b486-480f-bdb9-78672cd32584)

I can’t guarantee that I did everything correctly, but it seems that I went through all the options including those recommended before creating the issue.
In other themes, for example Colloid, there is no such problem, although looking at _common-3.0.scss I see that they differ in the FIle chooser section

### OS and version [e.g Fedora 37]

NixOS 23.11 (Tapir), VoidLinux

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

5.1

### GNOME version

44.0

### Application name and version (If the issue is with an app.)

Transmission 3.00

**Comment by lassekongo83** [comment]
The filechooser sidebar should be styled with `sidebar_bg_color`. So: `@define-color sidebar_bg_color pink` if you edit your gtk.css files. You'll need a nightly version of Gradience to use it.

**Comment by MOIS3Y** [comment]
Yes it works like a charm!
I just added it to ~/.config/gtk-3.0/gtk.css
```css
@define-color sidebar_bg_color rgb(30, 30, 46);
```
![2023-11-27_20-05](https://github.com/lassekongo83/adw-gtk3/assets/48302224/9e0e53f7-2604-4ca9-a175-4c0dee5bb2c2)



Thanks for the quick response.

For some ridiculous reason I missed this in [HOWTO](https://github.com/lassekongo83/adw-colors/blob/main/HOWTO.md) 

Thanks again, adw-gtk3 is the best way to make system-wide unified application design.
Please don't stop!

I think the issue can be closed since the problem is completely resolved.
