### ISSUE TITLE
Removing the active button background from the window buttons.

### ISSUE THREAD

**Issue by i2sage** [lassekongo83/adw-gtk3#248]
after following the steps from a old issue i was able to remove the window button background from inactive window but cannot seem to find a way to remove the background button from an active window. can u point out what should i do to remove it from active window too.

expected behaviour: 
[Screencast from 2023-12-25 18-20-43.webm](https://user-images.githubusercontent.com/137275372/292758232-37ff57d6-9da1-4042-a058-01c2a210dcc0.webm)
whats happening now:
[Screencast from 2023-12-25 18-19-44.webm](https://user-images.githubusercontent.com/137275372/292758277-15cdc72a-56de-49b8-8f77-e3dd1d5b2c66.webm)

https://github.com/lassekongo83/adw-gtk3/blob/ac710a7659621c8b41dc63adda05dc6b72d02820/gtk/src/adw-gtk3/gtk-3.0/_common.scss#L4612
https://github.com/lassekongo83/adw-gtk3/blob/ac710a7659621c8b41dc63adda05dc6b72d02820/gtk/src/adw-gtk3/gtk-3.0/_custom.scss#L480
https://github.com/lassekongo83/adw-gtk3/blob/ac710a7659621c8b41dc63adda05dc6b72d02820/gtk/src/adw-gtk3/gtk-3.0/_common.scss#L1687

_Originally posted by @lassekongo83 in https://github.com/lassekongo83/adw-gtk3/issues/204#issuecomment-1356653675_

**Comment by lassekongo83** [comment]
Change this to transparent.

https://github.com/lassekongo83/adw-gtk3/blob/ac710a7659621c8b41dc63adda05dc6b72d02820/gtk/src/adw-gtk3/gtk-3.0/_colors.scss#L113C19-L113C19
