### ISSUE TITLE
Lollypop does not use the dark theme

### ISSUE THREAD

**Issue by shadear** [lassekongo83/adw-gtk3#25]
Lollypop music player does not use the dark theme when applied globally, but when I set adw-gtk3 light theme globally and use the dark theme toggle within the app, there is no problem.

Video for better understanding:

https://user-images.githubusercontent.com/47904282/152676927-e260086d-4579-4e79-94f0-76119f10534c.mp4

**Comment by lassekongo83** [comment]
I can't reproduce. Try a relog.

**Comment by shadear** [comment]
After reinstalling it works fine, thanks for the theme and the quick reply!
