### ISSUE TITLE
Adw-gtk3 as default/official gtk3 adwaita theme for gnome

### ISSUE THREAD

**Issue by vovagorodok** [lassekongo83/adw-gtk3#255]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

Any pals to make it as default adwaita gtk3 theme in official repo? It look way more better and consistent that current official theme

### OS and version [e.g Fedora 37]

Fedora 39/40

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

N/A

**Comment by lassekongo83** [comment]
https://www.reddit.com/r/gnome/comments/syvj33/will_the_adwaita_theme_for_gtk_3_be_updated_to/hy03uss/
