### ISSUE TITLE
Firefox >=125.0 has incorrect spacing between CSD header buttons

### ISSUE THREAD

**Issue by TheBoctor** [lassekongo83/adw-gtk3#256]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [ ] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

As of Firefox 125.0, the header buttons on the application's CSD are closer together than intended, when using adw-gtk3 (general, not specific to light nor dark.)

Top bar with CSD enabled and default Adwaita GTK theme:
![image](https://github.com/lassekongo83/adw-gtk3/assets/45834980/e917f08e-6a7b-4cce-96b5-d82d1a681e62)
Top bar with CSD enabled and adw-gtk3-dark 5.3-2 from AUR:
![image](https://github.com/lassekongo83/adw-gtk3/assets/45834980/77a3ea4f-8ce6-4888-828d-449e59d432f1)

This issue is unrelated to any extensions. My only nonstandard configuration is using the "compact" density in Firefox, but changing the density setting does not affect CSD button spacing. The relevant issue on Mozilla's tracker, with some explanation in the comments, can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1448332).

### OS and version [e.g Fedora 37]

Arch Linux

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

5.3-2 (AUR)

### GNOME version

46.0

### Application name and version (If the issue is with an app.)

Firefox 125.0.1

**Comment by lassekongo83** [comment]
Seems like it is no longer possible to style Firefox by itself in a gtk theme.

**Comment by lassekongo83** [comment]
Fixed in Firefox 127.
