### ISSUE TITLE
Rounded Window Corners GTK3

### ISSUE THREAD

**Issue by LSeelig** [lassekongo83/adw-gtk3#263]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [ ] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

Non libadwaita GTK4 apps will round their top and bottom corners to match libadwaita when the theme is applied, but gtk3 ones don't. I would think GTK3 doesn't support it, and you seemed to confirm that without libhandy, they don't, but the repo screenshots show rounded corners, and some other issues mention them. Is this a bug? Or a known limitation?

Without theme:
![Before Theming](https://github.com/user-attachments/assets/26c1169c-c456-4c2c-878a-c7b0c778e774)

With adw-gtk3:
![After Theming](https://github.com/user-attachments/assets/eb38c9ad-839f-439a-aa8c-8c24d2e22687)

### OS and version [e.g Fedora 37]

Fedora 40

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

git main

### GNOME version

46

**Comment by lassekongo83** [comment]
Rounded corners only supported on libhandy applications or with the rounded corners extension.
