### ISSUE TITLE
accent color is not set when i choose it from settings

### ISSUE THREAD

**Issue by radical4ever** [lassekongo83/adw-gtk3#269]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

gnome 47 brings the capability to choose an accent color from the settings page, since i updated from 46 adw-gtk3 is unable to change its accent colour

### OS and version [e.g Fedora 37]

Fedora 41

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

5.4 (from dnf)

### GNOME version

47

**Comment by n3thshan** [comment]
> GTK3 does not support that.

would there be any other alternative ways youd suggest to change just the accent color.

**Comment by lassekongo83** [comment]
You can create `~/.config/gtk-3.0/gtk.css` and add for example:

```css
/* Replace #E95420 with any css color value */
@define-color accent_bg_color #E95420;
@define-color accent_color @accent_bg_color;
```

**Comment by eylles** [comment]
well, i got something of a duct tapey solution for this, thanks to @Neutrovertido and his https://github.com/Neutrovertido/adw-gtk2-accent-colors repo we got gradience templates for the accent colors, and i've recently pushed this script https://github.com/eylles/pywal16-libadwaita/blob/master/scripts/gradience2css.py that can take a gradience template and spit out the correct css to gtk-3.0 and gtk-4.0, i just have to functionalize the script a lot more, add a script to fetch and install the adw-gtk3 theme releses, glue evrything to a main and then package to pypi...

that should of provide a usable stop gap solution while i manage to revive gradience proper.

cc @TiZ-HugLife ya may find this interesting, or not :man_shrugging:
