### ISSUE TITLE
Window title bar look transparrent in Electron-based apps

### ISSUE THREAD

**Issue by Anifyuli** [lassekongo83/adw-gtk3#271]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

After updating Adw-gtk3 to v5.4, I get this problems. I report it on Nixpkgs issue tracker too cause this bugs in [here](https://github.com/NixOS/nixpkgs/issues/345084). I will attach some Electron-based apps screenshots.

VS Code
![image](https://github.com/user-attachments/assets/1b50d08e-6f68-472b-ba67-81af7f042498)
Youtube Music by th-ch
![image](https://github.com/user-attachments/assets/3ff6fe9c-4f38-4282-baf0-54b28fe904fc)

This bugs affected to installed apps from Flatpak too. I check my Inkscape and not affected with this bugs.

### OS and version [e.g Fedora 37]

NixOS 24.11.20240923.30439d9 (Vicuna) x86_64

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

NixOS unstable channel

### GNOME version

46.4

### Application name and version (If the issue is with an app.)

All Electron apps, such as VS Code, GDevelop, YouTube Music, Postman, etc

**Comment by lassekongo83** [comment]
5.4 requires GNOME 47 with GTK 4.16. Downgrade to 5.3.

**Comment by Anifyuli** [comment]
Thanks for your solutions
