### ISSUE TITLE
adw-gtk3 prevents firefox 133 to follow accent color

### ISSUE THREAD

**Issue by darkblaze69** [lassekongo83/adw-gtk3#277]
* GNOME 47.2
* adw-gtk3 5.5

firefox 133 now follows accent color, but adw-gtk3 prevents it

Without adw-gtk3:

![image](https://github.com/user-attachments/assets/0e40687a-de9c-451c-bf1d-ddebbea97989)

![image](https://github.com/user-attachments/assets/134b8b2b-6ac9-475e-bb19-16860a7b1ad4)

**Comment by lassekongo83** [comment]
This should be taken care if with a script. I don't know of any other way to change the accent color across various toolkits and applications: https://github.com/lassekongo83/adw-colors/tree/main/accent-color-change (Sorry no GUI.)
