### ISSUE TITLE
Discussion: Buttons should be bold

### ISSUE THREAD

**Issue by kk-mofux** [lassekongo83/adw-gtk3#28]
In libadwaita all buttons have a bold text. This helps to differentiate them from inputs.

Here is an example where the "Extract" Button should be bold:

![non-bold-button](https://user-images.githubusercontent.com/7723079/153905004-fdfa3936-6150-4ba7-89fd-5e70ce6fc3ad.png)

**Comment by kk-mofux** [comment]
Hmm, maybe status-quo (non-bold buttons in headerbars) is the correct way to go here. 

Libadwaita will put a background on buttons without icons in headerbars but i guess this is not doable in GTK3?

Bold buttons without the background would probalby interfere with the bold window label. Maybe it's possible to make them bold outside of headerbars though?

**Comment by lassekongo83** [comment]
The new update should bring the buttons a bit closer to libadwaita.

**Comment by kk-mofux** [comment]
:heart: thanks!
