### ISSUE TITLE
Disabled sliders

### ISSUE THREAD

**Issue by piotrzientarski** [lassekongo83/adw-gtk3#29]
Hi,
at first thanks for your hard work, all the themes you make are great.

I noticed a problem in Pavucontrol - sliders that are turned off are completely invisible. I don't know if it should be like that?

![Screenshot from 2022-02-16 10-47-09](https://user-images.githubusercontent.com/6192086/154238792-b980aeb6-f125-4906-8761-c352db9a0cfb.png)

**Comment by piotrzientarski** [comment]
Unfortunately, this change did not help, the problem still persists.

**Comment by IlChitarrista** [comment]
Hello, it seems as tho this issue has been correctly fixed.
![image](https://user-images.githubusercontent.com/86124987/154850967-3c86608c-a72b-4d41-a91e-44dc185a91dc.png)
![image](https://user-images.githubusercontent.com/86124987/154851000-c6c52c8f-53b6-4171-b6f8-6708a8c016c7.png)

The only thing I can note is that, in the dark theme, when the window is deselected, it might be almost invisible.
![image](https://user-images.githubusercontent.com/86124987/154851050-677938e1-71b4-451f-aaa1-45ec0c81dd12.png)
I'm not sure whether the way this is handled is enforceable by the theme but if it isn't this issue should be closed.
Thanks for reporting!

**Comment by piotrzientarski** [comment]
I confirm that the bug has been corrected.
As for me, the sliders look very good with both an active and inactive window.

**Comment by piotrzientarski** [comment]
I confirm that the bug has been corrected.
As for me, the sliders look very good with both an active and inactive window.

**Comment by piotrzientarski** [comment]
As for me, the sliders look very good with both an active and inactive window.
