### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by diego-pvlk** [lassekongo83/adw-gtk3#37]
- Borders are transparent. Libadwaita borders are solid (light: #CACACA, dark: #454545)
- Nautilus changes background to a lighter color when a new tab is opened
![nautilus1](https://user-images.githubusercontent.com/25941156/154814369-8e5917b1-b737-4174-afb7-feb04374d210.png)
![nautilus2](https://user-images.githubusercontent.com/25941156/154814371-69642eb7-e3ae-4884-a2d9-7d04c29ab56c.png)
- When hovering an inactive tab, the bottom border disappears
![tab-border](https://user-images.githubusercontent.com/25941156/154814420-4fba1c0b-2eda-4e34-9807-1651dfb899d2.png)
- Image viewer (Eye of GNOME) needs background color for the - and + buttons
![zoom-buttons](https://user-images.githubusercontent.com/25941156/154814417-7584d3ae-93cf-4555-b0cd-e87be850aece.png)
- Active text entries need better borders
![text-entry](https://user-images.githubusercontent.com/25941156/154814419-42127029-669c-4180-8a1b-2c1e356f4a52.png)
- Slider handle is dark instead of light on dark variant
![slider](https://user-images.githubusercontent.com/25941156/154814422-1adef6f0-1c1b-45ce-a1e3-cd6aecdab6ab.png)

**Comment by lassekongo83** [comment]
> Borders are transparent. Libadwaita borders are solid (light: #CACACA, dark: #454545)

Which borders?

**Comment by diego-pvlk** [comment]
Ops, I should be specific: window borders.

**Comment by lassekongo83** [comment]
All the window borders here use a transparent color: https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/widgets/_window.scss

And those libadwaita apps I have installed also seem to use a transparent border.

**Comment by diego-pvlk** [comment]
You're right they actually are transparent. But they are being rendered "inside" the window. See these images, it causes a different effect:
![1](https://user-images.githubusercontent.com/25941156/154817490-05931e4c-ebc3-4093-a23e-a50c25f4bf24.png)
![2](https://user-images.githubusercontent.com/25941156/154817491-681577d7-cef2-4da4-aa39-d9accffa05f7.png)

**Comment by lassekongo83** [comment]
Most of these should be fixed. Sliders are still on my todo list. Window borders are not possible to set as an inset with GTK3.

**Comment by IlChitarrista** [comment]
Hello @lassekongo83, I'm working on Sliders, It's my first ever contribution.
We just need the handle to be white in both variants right?

**Comment by lassekongo83** [comment]
@IlChitarrista I've actually finished some svg assets myself, so you don't have to. I just need to render them and change the code a bit. :wink:

**Comment by IlChitarrista** [comment]
Thanks!

**Comment by diego-pvlk** [comment]
> Window borders are not possible to set as an inset with GTK3.

What about setting $_wm_border to a solid color?
![calc1](https://user-images.githubusercontent.com/25941156/154855509-3da744b6-6662-4197-853a-c4ecb61b87e7.png)

Doesn't seem to bad. The problem with the transparent borders is that sometimes they are not visible, you can see this happening here (if your github theme is set to dark)

![calc2](https://user-images.githubusercontent.com/25941156/154856245-096f3ecd-f802-491a-a1d3-bbd6de4509b0.png)

**Comment by lassekongo83** [comment]
Seems ok enough, but only for the dark theme.

**Comment by diego-pvlk** [comment]
Awesome! 
I just noticed that this affects the context menus too. Not a big deal, looks quite nice actually because sometimes they blend with the background. But I guess a better design for this menu is on your todo list as well.
![](https://user-images.githubusercontent.com/25941156/154860296-e4e43f18-8163-4241-bf2c-ce501f4a415c.png)
