### ISSUE TITLE
[Buttons] Destructive action buttons don't get colored

### ISSUE THREAD

**Issue by DiegoMagdaleno** [lassekongo83/adw-gtk3#4]
## The bug

Buttons that are destructive (This means their actions destroy a process, for example "Don't save a file", "exit", "quit", "End process") don't get colored and instead show the background color with a white text, these makes them impossible to read

## Steps to reproduce

1. Open any app that has destructive actions (Like Gedit)
2. Write anything on it 
3. Try to close the window

## Screenshots

Here is an example with "end process" on GNOME System monitor:

![image](https://user-images.githubusercontent.com/38844659/150563282-65e06660-407f-4ad8-a478-7eaf6457a274.png)

Close without saving on Gedit:

![image](https://user-images.githubusercontent.com/38844659/150563327-64e9a529-3bd3-446b-96e1-853b55d1c1bc.png)

## Libadwaita apps screenshots

![image](https://user-images.githubusercontent.com/38844659/150563796-c504d43c-c508-4f06-b4ea-405b15a0482b.png)

## Original Adwaita screenshots (Current GNOME theme)

![image](https://user-images.githubusercontent.com/38844659/150564048-8b9a53cb-0ff5-43ba-b89e-f44494333b2e.png)

## Proposed

In the case you wish to reimplement the red, Libadwaita docs suggest this style:

![image](https://user-images.githubusercontent.com/38844659/150564252-b9b625f3-7757-4304-81c3-fd70481dbc67.png)

And the documentation can be found [here](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.0.0/style-classes.html)

**Comment by Sultech** [comment]
![image](https://user-images.githubusercontent.com/30802163/150575489-4696a8d7-1513-44e2-bba0-89e9cdfb5f1f.png)

**Comment by Sultech** [comment]
![image](https://user-images.githubusercontent.com/30802163/150576566-98cbaaa8-9481-46cd-b8cb-38eec31a4cfe.png)
![image](https://user-images.githubusercontent.com/30802163/150576650-b7b26aeb-6d1d-42e1-b4c5-b9b3866ad6a6.png)

**Comment by Sultech** [comment]
I just updated and the download and update buttons in gnome software are still not showing and the calculator is the same
