### ISSUE TITLE
Differences in Gnome Calculator

### ISSUE THREAD

**Issue by IlChitarrista** [lassekongo83/adw-gtk3#40]
Hello, let's compare adw-gtk3 to GTK4 to check for differences which might be solvable through the theme.

![image](https://user-images.githubusercontent.com/86124987/154856475-3e2fc571-bfdb-4735-961c-d4a0534baf0d.png)
![image](https://user-images.githubusercontent.com/86124987/154856483-f2c94721-f48b-4292-9e1a-d4d1d4ab9b49.png)

Is this fixable generally or does it need a specific rule (I'm mostly referring to the central widget)?

**Comment by RetronEletron** [comment]
No idea i had both of them and they look the same.

**Comment by IlChitarrista** [comment]
I think I should close this issue as the Libadwaita version is out; I wouldn't even have a way to test this.

**Comment by lassekongo83** [comment]
Agreed.
