### ISSUE TITLE
Differences in Gnome Calendar

### ISSUE THREAD

**Issue by IlChitarrista** [lassekongo83/adw-gtk3#41]
Let's compare adw-gtk3 to GTK4 in the Gnome Calendar to find differences solvable through the theme itself.
This Issue can be closed if what reported isn't related to the theme.

![image](https://user-images.githubusercontent.com/86124987/154856746-373710e6-1db4-4eac-86bf-4d548a5aa19c.png)
![image](https://user-images.githubusercontent.com/86124987/154856752-59e74e4d-20af-462e-9372-07b92c02e29e.png)

It's mostly titlebar buttons not being highlighted and the central menus being squared off.

**Comment by lassekongo83** [comment]
I haven't found a way to make libhandy viewswitcher buttons to look like normal buttons yet.

**Comment by diego-pvlk** [comment]
Is it even worth to fix styles for apps like gnome software, calculator, calendar, etc? Those apps will be updated to GTK4 in GNOME 42 and will use libadwaita.
Idk, unless the style applies to apps that are not going to receive updates, I don't see the point. But that is just my opinion.

About the viewswitcher, I managed to do this:
![](https://user-images.githubusercontent.com/25941156/155182825-18ab032c-ec9e-41a8-8599-3bb9f7dea35a.png)
But it also changes the narrow view (only headerbar):
![](https://user-images.githubusercontent.com/25941156/155182823-8c8c6d8f-852d-4397-85b7-7458e228d769.png)

Libadwaita is different:
![](https://user-images.githubusercontent.com/25941156/155182820-6f50bdc9-aaf8-4cf1-92d3-f06f0f479a72.png)

```
headerbar.windowhandle viewswitcher {
  button:not(.titlebutton):not(.suggested-action):not(.destructive-action) {
    border-radius: 6px;
    margin: 6px 2px;

    > stack > box.narrow { 
      padding: 0 8px;
    }
  }
}
```

**Comment by lassekongo83** [comment]
> Is it even worth to fix styles for apps like gnome software, calculator, calendar, etc? Those apps will be updated to GTK4 in GNOME 42 and will use libadwaita.

Not in Ubuntu 22.04.

**Comment by DuttaAB-dev** [comment]
No

> Is it even worth to fix styles for apps like gnome software, calculator, calendar, etc? Those apps will be updated to GTK4

Not in Cinnamon, Xfce, Mate, or other desktops that are gonna stick to gtk 3 and use some of these widgets for example the view switcher in some app's about section.

**Comment by diego-pvlk** [comment]
I was referring mostly to gnome apps, which you can install through flatpaks (software is an exception).

**Comment by IlChitarrista** [comment]
Now that the Libadwaita version is out should this issue be closed?
