### ISSUE TITLE
Nautilus header bar path widget padding error

### ISSUE THREAD

**Issue by juxuanu** [lassekongo83/adw-gtk3#50]
![imatge](https://user-images.githubusercontent.com/24759034/155106374-96c50fb3-0b3b-469c-a79d-641f421c488d.png)

**Comment by kk-mofux** [comment]
can confirm that bug, got the same here

**Comment by kk-mofux** [comment]
fixed, thx!

**Comment by kk-mofux** [comment]
i'm running nautilus 41.2 (Arch) fwiw

**Comment by bellegarde-c** [comment]
I'm running nautilus 42 beta

**Comment by bellegarde-c** [comment]
So I broke nautilus 41 with my merge request: https://github.com/lassekongo83/adw-gtk3/pull/47

:(

**Comment by bellegarde-c** [comment]
Ok, found, there is no menu button in nautilus 41. Will try to make a fix for both versions

**Comment by DuttaAB-dev** [comment]
Still broken for me after the update.

**Comment by bellegarde-c** [comment]
Did you quit nautilus ?

**Comment by kk-mofux** [comment]
yes, i think when i saw the glitched i closed and reopened it

**Comment by bellegarde-c** [comment]
@lassekongo83 Will send you a new pull request with Nautilus 42 support and you will have to wait before merging it :)
