### ISSUE TITLE
Incorrect theming of the gnome software.

### ISSUE THREAD

**Issue by DuttaAB-dev** [lassekongo83/adw-gtk3#52]
All the app cards lack a shadow while using the adw-gtk3 theme.

libadwaita:
![image](https://user-images.githubusercontent.com/61903332/155177081-0b2dac96-feb2-4732-a0b9-cf90a5508996.png)

adw-gtk3:
![image](https://user-images.githubusercontent.com/61903332/155177193-53f85503-edf1-4b24-80ec-cde2b26ac616.png)

Also the border colour is different.

Lastly, there is no padding at the bottom of the list view in the "software repositories" menu. I don't know if this is the same in other places as I havent' tested/noticed this anywhere else yet.

adw-gtk3:
![image](https://user-images.githubusercontent.com/61903332/155177956-6bbef1d7-c5a3-4194-9518-9eb8bb2583ff.png)

libadwaita:
![image](https://user-images.githubusercontent.com/61903332/155178138-335e94b1-70b0-46d2-92d4-571863793829.png)

adwaita theme:
![image](https://user-images.githubusercontent.com/61903332/155178289-e129adcc-abbc-461c-8d2a-9e0fc1a96157.png)

**Comment by lassekongo83** [comment]
I had the padding issue in nautilus preferences as well. I solved it with:
```css
.preferences scrolledwindow > .frame > clamp {
  &.large, &.medium, &.small { padding-bottom: 30px; }
}
```
But from what I saw it was no preferences page, and I had only one row, so I couldn't test anything.

Since adwaita have it at normal padding, there must be some missing css somewhere.

**Comment by xAspirus** [comment]
shouldn't we focus only on the apps which are not going to be ported over to gtk-4?

**Comment by DuttaAB-dev** [comment]
> shouldn't we focus only on the apps which are not going to be ported over to gtk-4?

I guess you are right, but then ubuntu is gonna stick to not using libadwaita while still using gtk4 apps without the libadwaita port, for example Nautilus 42. So maybe correcting the theming in this case might help in solving some issues in ubuntu 22.04

**Comment by DuttaAB-dev** [comment]
![image](https://user-images.githubusercontent.com/61903332/155693410-411e8821-cbee-4861-840a-b1b3ae3c4ff9.png)
Btw, commit bccba2288a87e4a19797c3656cb9db03377259da, i.e. the latest commit that you made on this issue did not fix it in my case.

**Comment by juxuanu** [comment]
Also, 
![imatge](https://user-images.githubusercontent.com/24759034/155712325-8933cd46-d08e-427f-8024-6b25e126a87d.png)
