### ISSUE TITLE
Active switch colour different from libadwaita.

### ISSUE THREAD

**Issue by DuttaAB-dev** [lassekongo83/adw-gtk3#53]
Libadwaita uses `#3584E4` for the blue part of an active switch in both light and dark modes
![image](https://user-images.githubusercontent.com/61903332/155180240-acd8da0f-0b98-4642-a696-c6289487b85b.png)

While, adw-gtk3 uses `#418CE6` for active switches, which is much lighter.
![image](https://user-images.githubusercontent.com/61903332/155181861-4eedd48a-3664-4bd7-a652-e98f216f4df0.png)

It is to be noted that in libadwaita, the colour of the active switch changes to `#4990E7` when the mouse pointer directly hovers over it.
![image](https://user-images.githubusercontent.com/61903332/155182390-6959271f-a9b1-475c-b6ec-23f3caa1c9d8.png)

While, nothing much happens in adw-gtk3 while hovering the mouse pointer over a switch.

**Comment by DuttaAB-dev** [comment]
Also, now that I am looking at them next to each other, the switches/sliders in libadwaita are much thinner compared to adw-gtk3 or the default adwaita theme.

**Comment by lassekongo83** [comment]
This should be fixed in https://github.com/lassekongo83/adw-gtk3/commit/fe780b978be09544fb1a09d969b9601912a7312f

**Comment by DuttaAB-dev** [comment]
>  The smaller size may be a setting on your end, or the application you're using. 

Yeah, you are probably right as it maybe an artifact of using gnome 42 beta in a vm with a lower resolution.
