### ISSUE TITLE
Invalid backdrop for suggestion button in headerbar

### ISSUE THREAD

**Issue by bellegarde-c** [lassekongo83/adw-gtk3#55]
Exemple with gnome-screenshot:

![Screenshot from 2022-02-24 08-05-05](https://user-images.githubusercontent.com/57196916/155474946-c6a559d5-cdc8-4bdf-994d-71957784db02.png)

**Comment by lassekongo83** [comment]
Which color is it supposed to be? Adwaita-1-demo doesn't really show anything like it.

**Comment by bellegarde-c** [comment]
Yes, looks like color are not dimmed when window is inactive in demo :(

**Comment by bellegarde-c** [comment]
![Screenshot from 2022-02-24 08-28-43](https://user-images.githubusercontent.com/57196916/155478153-94a28df1-9bff-4b46-8c54-c1f5ed5e46c9.png)
