### ISSUE TITLE
Incorrect colors for the page search box on Chromium/Google Chrome for light style scheme

### ISSUE THREAD

**Issue by rmnscnce** [lassekongo83/adw-gtk3#56]
Operating System: Fedora 35 Workstation x86_64
GTK3 version: 3.24.31 (packaged as `gtk3-3.24.31-2.fc35.x86_64`)
Chromium/Google Chrome version: Google Chrome 98.0.4758.102 (Official Build) (64-bit) (packaged as `google-chrome-stable-98.0.4758.102-1.x86_64`)
Git commit of theme: f7ed2ab

It appears that Chromium picks up the same color as the inactive omnibox background for the page search box background.

## Examples:
adw-gtk3:
![image](https://user-images.githubusercontent.com/31619874/155545997-392c518b-eca6-4393-9ba2-3f0ad14febad.png)

Adwaita:
![image](https://user-images.githubusercontent.com/31619874/155545858-fc6b64db-cb67-45bb-8ffe-0fcc27d3e424.png)

**Comment by rmnscnce** [comment]
Additional information:
It seems like applications set colors for text box backgrounds differently. GNOME Text Editor and the Adwaita Demo app have different opinions on how to color a text box:

- GNOME Text Editor: white text box backgrounds, for both inactive and active states
![image](https://user-images.githubusercontent.com/31619874/155547628-97c5451a-8765-4fca-9575-50e09d4c44d9.png)

- Adwaita Demo: gray text box background, for both inactive and active states
![image](https://user-images.githubusercontent.com/31619874/155547709-010ad777-342e-42e7-b3e4-f82748ca3462.png)



I personally think GNOME Text Editor's colors are better for such fields.

**Comment by lassekongo83** [comment]
@diego-pvlk Any input on how the chromium issue can be resolved, or if that's the intended look?

As for the second issue. This theme follows the styles that can be found in `adwaita-1-demo` and when using the libadwaita theme in `gtk4-widget-factory`, not the styles individual apps choose to use.

**Comment by diego-pvlk** [comment]
I don't think it's possible to change the omnibox and search box individually, so you have to make a personal choice on which one looks better. I was trying to make the light omnibox looks more like nautilus pathbar. 

The color to change is here:
https://github.com/lassekongo83/adw-gtk3/blob/f7ed2ab0c6ec9954f40b75b6bba326ae6b5b8db5/gtk/src/adw-gtk3/gtk-3.0/_apps.scss#L601-L603
