### ISSUE TITLE
Hovering over items

### ISSUE THREAD

**Issue by Sultech** [lassekongo83/adw-gtk3#6]
when hovering over any of these updates the selection does not go to the end.
![image](https://user-images.githubusercontent.com/30802163/150584028-34dc0178-fe7e-47cd-8c68-bdd9ed5df5fb.png)
same with gnome tweaks on any of the sections.
![image](https://user-images.githubusercontent.com/30802163/150584555-091ff556-a841-447c-b572-70bf51d1f6f0.png)
With normal adawaita the blue goes to the end
![image](https://user-images.githubusercontent.com/30802163/150584761-e852b784-98ba-4fc8-8a11-2d225b0afdca.png)

**Comment by lassekongo83** [comment]
That's the indented behavior. https://blogs.gnome.org/alexm/files/2021/12/Screenshot-from-2021-12-31-14-05-13.png

It may need some refinements tough.
