### ISSUE TITLE
Nautlius not using correct theme in gnome 42 if adw-gtk3-dark is selected

### ISSUE THREAD

**Issue by jdamboeck** [lassekongo83/adw-gtk3#62]
When i select the Dark Style in gnome-settings 42 and combined it with adw-gtk3-dark in  gnome-tweaks nautilus looks like this.
![Screenshot from 2022-03-04 01-25-31](https://user-images.githubusercontent.com/20957463/156676095-968d1366-7a2a-4bbc-80a1-a7e52fcef010.png)

Only when selecting the adw-gtk3 style and reselecting the dark style in gnome-settings nautilus uses the libadwaita styles.
![Screenshot from 2022-03-04 01-26-00](https://user-images.githubusercontent.com/20957463/156676184-ce24349b-afb4-48da-9d9b-5537bc130c02.png)

Gnome version 42.beta / Nautilus 42.rc

btw: Thx for over a decade of your high quality themes on my computer

**Comment by Sowgro** [comment]
I have the same issue, it happens on many other apps that come with fedora. I noticed it on Disks, Image viewer and System Monitor just to name a few.

**Comment by lassekongo83** [comment]
Does it work if you copy `gtk-dark.css` from the light theme to the dark theme?

**Comment by ramottamado** [comment]
It's because Nautilus and the majority of gnome apps have been already ported to GTK4 with libadwaita. They don't respect the CSS stylesheet anymore.

**Comment by DuttaAB-dev** [comment]
> It's because Nautilus and the majority of gnome apps have been already ported to GTK4 with libadwaita. They don't respect the CSS stylesheet anymore.

I heard that the nautilus port to libadwaita will not be ready in time for gnome 42 stable, and hence wont be released and the old gtk4 version of nautilus will be used..,

**Comment by lassekongo83** [comment]
Nautilus 42 is GTK3.

**Comment by DuttaAB-dev** [comment]
> Nautilus 42 is GTK3.

I mean yeah gtk3, not 4

**Comment by jdamboeck** [comment]
@[lassekongo83 copying the dark.css works.
