### ISSUE TITLE
Drop down toggle has the incorrect color in the "Getting Things GNOME!" app

### ISSUE THREAD

**Issue by rmnscnce** [lassekongo83/adw-gtk3#63]
Flatpak runtime: GNOME 41 (Flatpak runtime) (`org.gnome.Platform/x86_64/41` from Flathub)
Flatpak runtime commit: `b0aed9b5fb8b5e3e1e1badc8711fa34667760cf5ce79b2727b8d8c21d4772577`
App version: 0.6 from Flathub (`org.gnome.GTG`)
App Flatpak commit: `a48d70f74f2df27215f365840a928e714193ee9779a65b93bb4669f9d02f74ee`
Git commit of theme: a1e1867

It appears that the theme applies incorrect colors for the drop down toggle button in the app.

# Examples:
---
adw-gtk3:
![image](https://user-images.githubusercontent.com/31619874/156734588-936b7a49-1ae7-4141-8c4b-8b1d7f6becf7.png)

Adwaita:
![image](https://user-images.githubusercontent.com/31619874/156734661-f9d7292d-f75b-4747-85a7-b6d32966181f.png)

adw-gtk3-dark:
![image](https://user-images.githubusercontent.com/31619874/156734719-7826076e-97ab-421d-9cf7-567bf59a662b.png)

Adwaita-dark:
![image](https://user-images.githubusercontent.com/31619874/156734750-0cd9374b-4ed1-43b7-bb20-2a5e6abc2c43.png)

**Comment by bellegarde-c** [comment]
Here, this one is not fixed

**Comment by bellegarde-c** [comment]
![image](https://user-images.githubusercontent.com/57196916/157613539-9fc6280e-1273-40cb-805d-136a05c9ca85.png)

**Comment by lassekongo83** [comment]
Flatpak version?

**Comment by bellegarde-c** [comment]
OMG, I'm too stupid :-) Sorry for noise
