### ISSUE TITLE
Firefox Enhancement Patch?

### ISSUE THREAD

**Issue by CleoMenezesJr** [lassekongo83/adw-gtk3#68]
Is there any possibility that there is a patch to improve the contrast in Firefox? It is one of the most used browsers on Linux, it would be great to be able to have a cuddle with it.

Idle
![Captura de tela de 2022-03-10 18-25-15](https://user-images.githubusercontent.com/54215258/157757828-70abee8d-8a48-46e7-8c0b-457eddc1a571.png)
Hover tab
![Captura de tela de 2022-03-10 18-25-36](https://user-images.githubusercontent.com/54215258/157757829-ea82ef24-67a9-4675-b039-f5376deb67dc.png)

**Comment by CleoMenezesJr** [comment]
Thank you very much for the speed with which you solved the problem. Hope to see this soon on the flathub.

**Comment by CleoMenezesJr** [comment]
The change was not applied to Firefox Flatpak :/

**Comment by lassekongo83** [comment]
You may have to install the flatpak theme as root if firefox was installed as root.

**Comment by CleoMenezesJr** [comment]
> You may have to install the flatpak theme as root if firefox was installed as root, and vice versa.

All my flatpaks apps are installed as user. It is interesting that this is already another installation and the colors are inverted when the window is selected and when it is not.

**Comment by lassekongo83** [comment]
After some more testing. Firefox flatpak doesn't support the dark theme switcher in GNOME 42. So you'll have to make sure you have selected the dark theme in gnome-tweaks and have the adw-gtk3-dark flatpak installed. Then restart firefox.

**Comment by CleoMenezesJr** [comment]
I just installed Firefox stable to do a couple of tests and I just noticed that it works without any problem, I believe the problem maybe is that Firefox beta is not supported?
