### ISSUE TITLE
Flat buttons are not flat

### ISSUE THREAD

**Issue by AdrianVovk** [lassekongo83/adw-gtk3#69]
I'm using adw-gtk3 to style my desktop environment's shell to look like libadwaita (unfortunately, I can't port it to gtk4 quite yet). I have various buttons that are using the `.flat` style class. A recent update in adw-gtk3 broke these buttons. See images

![20220323_01h17m39s_grim](https://user-images.githubusercontent.com/11251606/159628961-99e18c0e-633c-4045-b378-6e9b75b55426.png)
![20220323_01h17m28s_grim](https://user-images.githubusercontent.com/11251606/159628962-7365c2c4-ccf2-4320-ab78-cc05512e7e9a.png)

This is what it's supposed to look like (using a workaround):
![20220323_01h18m45s_grim](https://user-images.githubusercontent.com/11251606/159629084-f2f605e2-ac73-4a0c-bcc4-1c52ebc08586.png)
![20220323_01h18m41s_grim](https://user-images.githubusercontent.com/11251606/159629085-1013e13e-5c3d-41ac-bd6e-072777e6e61c.png)

**Comment by lassekongo83** [comment]
Is the menu a titlebar/headerbar, or a notebook?

**Comment by AdrianVovk** [comment]
whoops this isn't gitlab
