### ISSUE TITLE
flickering with buttons in HdySqueezer

### ISSUE THREAD

**Issue by Prince781** [lassekongo83/adw-gtk3#7]
GNOME Weather 41.0 displays this weird behavior when enabling the theme:

https://user-images.githubusercontent.com/1341033/150591110-514bef7b-8094-496f-a315-1999f0de1cbb.mp4

**Comment by lassekongo83** [comment]
Going to need more information here. Are you using the latest revision? Have you made any custom changes to `~/.config/gtk-3.0/gtk.css`? What font and font-size are you using?

**Comment by Prince781** [comment]
I'm using the adw-gtk3 AUR package and I installed it today. No modifications have been made. And I'm using the Cantrell font.

**Comment by lassekongo83** [comment]
Did the latest commit fix the issue?

**Comment by Sultech** [comment]
The latest commit has not fixed the issue

**Comment by Prince781** [comment]
@lassekongo83 thank you for your amazing work. :)
