### ISSUE TITLE
Dark google chrome

### ISSUE THREAD

**Issue by ShivamJoker** [lassekongo83/adw-gtk3#70]
Is there any way we can make the theme adapt google chrome as well?

**Comment by diego-pvlk** [comment]
It should be, can you post a screenshot?

**Comment by ShivamJoker** [comment]
I changed the theme to dark one but still no effect, Using your arch package in my manjaro btw
![image](https://user-images.githubusercontent.com/23727670/160488823-d65864d1-e29f-4b5b-8e02-a8ea59ffc7c1.png)

**Comment by diego-pvlk** [comment]
That's the correct theme, not much can be done about chrome other than changing some colors. 
I think you're confused, I'm not the owner of this repo or the arch package :P

**Comment by lassekongo83** [comment]
The start page can't be styled with gtk, it's html.

**Comment by ShivamJoker** [comment]
@lassekongo83 but in macos and windows it's dark as well if we enable dark mode in system settings and also all the sites will get a prefer color scheme dark.

**Comment by lassekongo83** [comment]
[It's an issue with chromium.](https://bugs.chromium.org/p/chromium/issues/detail?id=998903)

**Comment by ShivamJoker** [comment]
I was trying because gnome 42 added the systemwide dark mode support but the force dark mode just inverts all the colors which is bad.

**Comment by ShivamJoker** [comment]
Same goes for telegram as well auto dark mode stuff don't work
