### ISSUE TITLE
Electron Menu bar have the wrong color

### ISSUE THREAD

**Issue by snaggen** [lassekongo83/adw-gtk3#73]
Using the dark variant, I still get a light menu bar in Electron apps. This menu is dark when using the regular Adwaita-dark theme.

![bild](https://user-images.githubusercontent.com/6420639/160998440-dc6055b1-5323-41ec-81bf-5a43fce20d4f.png)

**Comment by lassekongo83** [comment]
Which application is it?

**Comment by snaggen** [comment]
I have verified this with Slack and Signal from Flathub

**Comment by lassekongo83** [comment]
Do you have the dark flatpak theme installed? `flatpak install org.gtk.Gtk3theme.adw-gtk3-dark`

**Comment by snaggen** [comment]
That and a restart solved my issue. Thanks for the help
