### ISSUE TITLE
adw-gtk3-qt?

### ISSUE THREAD

**Issue by julianfairfax** [lassekongo83/adw-gtk3#74]
I don't know exactly how https://github.com/FedoraQt/adwaita-qt is made. I suppose if it's a complete recreation of the adwaita theme in qt, then doing the same for this theme wouldn't be very possible for you, but if it's somehow a copy of it or something, maybe a adw-gtk3-qt theme could be made?

**Comment by lassekongo83** [comment]
Someone with more knowledge of qt would have to look into it. This repository is gtk3 only.
