### ISSUE TITLE
[Question] How to remove circle behind the window controls?

### ISSUE THREAD

**Issue by arun54321** [lassekongo83/adw-gtk3#75]
Not an issue. Could you tell me how to remove circles on the title bar on your theme?

I have managed to remove circles from gtk4 apps with
```
windowcontrols button image:not(:hover) {
background-color: transparent;
}
```
I like to get that similar look on gtk3 apps with your theme.

**Comment by lassekongo83** [comment]
`button.titlebutton { background-color: transparent; }`
