### ISSUE TITLE
Work on Phosh

### ISSUE THREAD

**Issue by julianfairfax** [lassekongo83/adw-gtk3#76]
Currently, installing this theme on Phosh will leave you with something that doesn't really look or work properly. I don't know why this is, but it'd be nice if this theme supported Phosh.

**Comment by julianfairfax** [comment]
In apps it seems to work, but Phosh itself and the keyboard are not properly themed. Not sure what info you need to be able to fix that, but here's Phosh's source code: https://gitlab.gnome.org/World/Phosh/phosh and the keyboard's source code: https://gitlab.gnome.org/World/Phosh/squeekboard

**Comment by lassekongo83** [comment]
I'm unable to test this, but do you get any result if you add `sq_button { background: pink; }` to `~/.config/gtk-3.0/gtk.css` ? (You may need to relog after doing that.)

**Comment by julianfairfax** [comment]
> I'm unable to test this, but do you get any result if you add `sq_button { background: pink; }` to `~/.config/gtk-3.0/gtk.css` ? (You may need to relog after doing that.)

Yes, my keys are now pink

**Comment by lassekongo83** [comment]
Let me know if the new added style fixed anything.

**Comment by julianfairfax** [comment]
This does style Squeekboard but does not solve the issues with themeing Phosh.

**Comment by julianfairfax** [comment]
@lassekongo83 As you can see the problem is with the styling of the Phosh interface itself. This is what it looks like with adw-grk3:
![adw-gtk3](https://user-images.githubusercontent.com/43753131/164483409-af44b186-b558-48b8-9143-f90b4f223f67.png)
![adw-gtk3-dark](https://user-images.githubusercontent.com/43753131/164483419-619f4cb0-097c-4ba8-bb
![adw-gtk3-phosh](https://user-images.githubusercontent.com/43753131/164483453-a25d41a2-a718-4a76-aa90-a5aa821dfafa.png)
bc-80d764a57cc8.png)

And this is what it normally looks like:
![Adwaita](https://user-images.githubusercontent.com/43753131/164483515-a055071c-08dd-42b1-bcdc-01d313d2580d.png)
![Adwaita-dark](https://user-images.githubusercontent.com/43753131/164483528-ecbc2537-79a5-4264-90b7-3b60552608b0.png)
![Adwaita-phosh](https://user-images.githubusercontent.com/43753131/164483537-656a7fe7-e8da-429a-81d1-31998eee918c.png)

**Comment by lassekongo83** [comment]
I'll have to wait to try and fix anything of this software until I've found a way to easily test it.

**Comment by CorvetteCole** [comment]
@lassekongo83 I'd probably be willing to lend you a pinephone if you want. Although it does run in a VM as well, I'll look for the information on that

**Comment by lassekongo83** [comment]
So I tried it in a WM. Other than some rounded corners I couldn't see what was wrong. Everything seemed to work and looked ok.

**Comment by julianfairfax** [comment]
> So I tried it in a WM. Other than some rounded corners I couldn't see what was wrong. Everything seemed to work and looked ok.

Can the rounded corners be fixed then? Also it doesn't seem that the phosh launcher and notification view are themed at all. Apart from the rounded corners that shouldn't be there.

**Comment by lassekongo83** [comment]
Let me know if the new styles fixed anything.

**Comment by julianfairfax** [comment]
They do. However, the rounded lighter box still shows up briefly when I click on the notification view to bring it down, or on the bottom to close an app. The close app toolbar interface then also shows this. I can send a video to demonstrate if you want?

**Comment by lassekongo83** [comment]
A video would be useful.

**Comment by julianfairfax** [comment]
Can't send it directly through GitHub but here you go: https://send.vis.ee/download/92ede1807350df1a/#hHHDs3xUXu18IdZSHc-jKA

**Comment by julianfairfax** [comment]
When you switch apps, as in click the bottom toolbar, and open another, the rounded lighter box also comes back until you close that app.

**Comment by lassekongo83** [comment]
Exactly what is "the rounded lighter box"?

**Comment by julianfairfax** [comment]
It's the light grey box you see that shows up in that video when I click the notification view, and on the bottom toolbar. When the toolbar goes from being fully grey to different shades. The first two screenshots here are what those two things look like normally, followed by an example of what I'm talking about.

![Screenshot from 2022-07-02 16-11-35](https://user-images.githubusercontent.com/43753131/177004394-fcd9b773-9de3-495d-8bf1-33fcc26fe9d0.png)
![Screenshot from 2022-07-02 16-11-40](https://user-images.githubusercontent.com/43753131/177004393-46282251-11b0-4cf3-b991-f792a638ae20.png)
![Screenshot from 2022-07-02 16-12-06](https://user-images.githubusercontent.com/43753131/177004392-34fc7350-32c4-43dc-942e-4ac453d9a08a.png)
![Screenshot from 2022-07-02 16-12-13](https://user-images.githubusercontent.com/43753131/177004391-db94a757-caf6-400c-b576-e8b03e834656.png)

**Comment by lassekongo83** [comment]
Unable to find a solution at the moment. `.phosh-panel-btn:active { background:transparent; }` works in gtk inspector, but not when applied to the theme.

**Comment by julianfairfax** [comment]
> Unable to find a solution at the moment. `.phosh-panel-btn:active { background:transparent; }` works in gtk inspector, but not when applied to the theme.

Hmm. If just that specific solution is a problem, can't you set the background to a colour, but just the same colour as the element behind it?

**Comment by lassekongo83** [comment]
Then I would have to set it as the same color as the current active color (which isn't black).

*But IMO a pressed state on the button isn't so bad as it indicates that the element is pressed. I personally found the default theme to be a bit confusing on that matter.*

**Comment by julianfairfax** [comment]
> Then I would have to set it as the same color as the current active color (which isn't black).
> 
> _But IMO a pressed state on the button isn't so bad as it indicates that the element is pressed. I personally found the default theme to be a bit confusing on that matter._

True, but in that case it should cover the whole element rather than just part of it with a rounded corner, and it shouldn't be as light.

**Comment by lassekongo83** [comment]
Managed to find a solution.

**Comment by julianfairfax** [comment]
Perfect. Thank you for working on this!
