### ISSUE TITLE
Firefox tab colors

### ISSUE THREAD

**Issue by alissonlauffer** [lassekongo83/adw-gtk3#78]
Starting with Firefox 99, tab colors are the same as the headerbar background. I Also noticed that there's a small difference while using the Default (Adwaita) theme, but color difference is still ok while using it.

### Adw-gtk3
Before:
![Screenshot from 2022-04-06 03-38-43](https://user-images.githubusercontent.com/29029632/161911053-1d6aafa7-1e83-47d0-b229-03a77b1fa67f.png)
Now:
![Screenshot from 2022-04-06 03-38-33](https://user-images.githubusercontent.com/29029632/161911072-3b37195a-d114-49ec-bfe9-ee5985aedad3.png)

### Default (Adwaita)
Before:
![Screenshot from 2022-04-06 03-49-05](https://user-images.githubusercontent.com/29029632/161912679-2da5c302-96f7-425d-9708-a8b0ea1f0d2a.png)
Now:
![Screenshot from 2022-04-06 03-49-35](https://user-images.githubusercontent.com/29029632/161912728-5fd00c61-3752-445b-bdc7-7275f1c40eb2.png)

**Comment by alissonlauffer** [comment]
Thanks for the quick fix!

Just noticed that the password input now looks a bit weird:

![Screenshot from 2022-04-06 04-35-06](https://user-images.githubusercontent.com/29029632/161920908-161d9ce4-5d2a-4420-812e-325431b79735.png)

**Comment by lassekongo83** [comment]
The update is not perfect and it may leave a weaker color on older versions of Firefox. It's so hard to find any documentation about the gtk widgets available. Gtk inspector doesn't show anything useful.

**Comment by emilio** [comment]
FYI this is probably https://bugzilla.mozilla.org/show_bug.cgi?id=1757506, which will be fixed in FF 100.

**Comment by alissonlauffer** [comment]
> FYI this is probably https://bugzilla.mozilla.org/show_bug.cgi?id=1757506, which will be fixed in FF 100.

Yeah, indeed. When I tested it, I did also test with Firefox Nightly. Firefox Nightly also had the same issue (And I thought it wasn't an issue, since it looks _ok_ with the default Adwaita theme). So maybe this patch can be reverted after Firefox 100 is being rolled out?

**Comment by laurinneff** [comment]
Not a solution, but maybe check out [firefox-gnome-theme](https://github.com/rafaelmardojai/firefox-gnome-theme)? Its libadwaita variant isn't officially released yet, but it already works really well. You can find it on the libadwaita branch.

**Comment by emilio** [comment]
I'm generally wary of external themes btw, if only because they don't get so much testing. E.g., https://bugzilla.mozilla.org/show_bug.cgi?id=1759409 was caused by the Manjaro fork of the firefox-gnome-theme, and it was kind of a pain to diagnose because, well, we can't easily repro those kinds of issues (we didn't even know that user had that theme installed, and the user didn't either).

But of course at your own risk and such :)
