### ISSUE TITLE
Border vanishes when tiled to an edge

### ISSUE THREAD

**Issue by moshiur-raj** [lassekongo83/adw-gtk3#79]
Native libadwaita app:
![image](https://user-images.githubusercontent.com/36466700/162134793-28585583-8f31-41d4-81c2-a3a3c375a064.png)
App using adw-gtk3:
![image](https://user-images.githubusercontent.com/36466700/162134852-2938979f-4b80-4570-b5f4-183046e9b9ba.png)

The borders on top and the left side are not present when using adw-gtk3.

**Comment by lassekongo83** [comment]
Nothing can be done about that as it's only possible to use box-shadows as borders (as far as I know), and those are outside the window and won't stick to edges etc.
