### ISSUE TITLE
[Tabs] Wrong colors

### ISSUE THREAD

**Issue by SilverMarcs** [lassekongo83/adw-gtk3#8]
Tabs seem to use slightly off colors for both active and inactive tabs. The case is same for dark mode too.

**adw-gtk3:**
![image](https://user-images.githubusercontent.com/77480421/150666801-10f47b14-aab5-4457-8f79-a5e794792e5b.png)

**Libadwaita:**
![image](https://user-images.githubusercontent.com/77480421/150666847-3b561658-4962-4138-98aa-1d5722cd2ae1.png)

**Comment by lassekongo83** [comment]
I have not tested this with the dark theme yet.

**Comment by Sultech** [comment]
Here are some images of apps after this change. I think the old colours looked better 

adw-gtk3 before change:
![lutris old](https://user-images.githubusercontent.com/30802163/150904301-9e8211f5-5897-4e22-9dc6-923353d5976d.png)
adw-gtk3 after change:
![lutrisnew](https://user-images.githubusercontent.com/30802163/150904293-c4711596-78b0-412d-a144-76f495effd4f.png)

adw-gtk3 before change:
![gnome software old](https://user-images.githubusercontent.com/30802163/150904302-030f7704-2889-4daf-ab67-38434e829979.png)
adw-gtk3 after change:
![gnome software new](https://user-images.githubusercontent.com/30802163/150904303-78485417-3e34-44f9-bd3c-7a1d85a461cb.png)

**Comment by xsrvmy** [comment]
This is being worked on upstream actually.
And there are some discussions around the UX of this anyways (dark inactive has almost same color as window content, when usually the active tab has the same color).
