### ISSUE TITLE
GTK2 windows are left unthemed

### ISSUE THREAD

**Issue by hmlendea** [lassekongo83/adw-gtk3#84]
Hello,

Is there any plan to support GTK2 also?
There are apps such as GIMP or Citrix and others, that are left unthemed and look like they run on Windows 98.

If not, is there a workaround to have the default Adwaita theme used for GTK2 while also using adw-gtk3 for GTK3?

**Comment by Tomoghno** [comment]
> Hello,
> 
> Is there any plan to support GTK2 also? There are apps such as GIMP or Citrix and others, that are left unthemed and look like they run on Windows 98.
> 
> If not, is there a workaround to have the default Adwaita theme used for GTK2 while also using adw-gtk3 for GTK3?

It would be very nice if they implemented GTK2 theme.

**Comment by Spike29** [comment]
There are a few tools to configure the GTK2 theme only: https://wiki.archlinux.org/title/GTK#Configuration_tools
I used "gtk-chtheme" which is available in the Arch repositories, it works well. Maybe it's available in other distros repositories too.

**Comment by lassekongo83** [comment]
Not worth the effort just for just a few legacy applications. And gimp have its own themes.

**Comment by Putu-Justine** [comment]
> Not worth the effort just for just a few legacy applications. And gimp have its own themes.

what about qt5-styleplugins that need gtk2? qgnomeplatform theming isn't good as QGtkStyle do.
what i referring to, is this : https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle

**Comment by eylles** [comment]
hi @lassekongo83 i cobbled together a repo [adw-gtk2-colorizer](https://github.com/eylles/adw-gtk2-colorizer) to more or less follow the styling (as good as possible that is) of adw-gtk3 in gtk2, along a python script that can be used to recolor said gtk2 theme from a gradience preset.

don't worry i won't require involvement from you other than consider adding it to the adw-gtk3 readme and mention it as an addon for those that do need support for legacy apps.

**Comment by amethystgosling163** [comment]
> hi @lassekongo83 i cobbled together a repo [adw-gtk2-colorizer](https://github.com/eylles/adw-gtk2-colorizer) to more or less follow the styling (as good as possible that is) of adw-gtk3 in gtk2, along a python script that can be used to recolor said gtk2 theme from a gradience preset.
> 
> don't worry i won't require involvement from you other than consider adding it to the adw-gtk3 readme and mention it as an addon for those that do need support for legacy apps.

Gradience is dead/ unmaintained and isn't even available on Flathub meaning that one cannot make use of this project to make GTK2 apps look native so I think adw-gtk3 should instead provide a GTK2 variant if only for the sake of coherence in the system no matter what toolkit is used but for the main reason to provide a proper theme for GTK2 apps so they look somewhat modern and aren't left un-themed.

**Comment by eylles** [comment]
@amethystgosling163 huh i didn't notice gradience was as good as dead... well it seems i may have to bite a bullet cuz i was using gradience as a way of "no think" theme gtk stuff, i already had plans to rip out only the parts of gradience in charge of taking the theme templates and outputting the css for adw-gtk3 and doing whatever flatpaks stuff needs done to be themed... now i got even more reasons to do that before the end of the year...
