### ISSUE TITLE
Inconsistent titlebar styling across apps

### ISSUE THREAD

**Issue by logant547** [lassekongo83/adw-gtk3#86]
![Screenshot from 2022-04-09 15-28-56](https://user-images.githubusercontent.com/45543257/162554747-21b7d282-a8d4-448e-b713-5137225d172f.png)
![Screenshot from 2022-04-09 15-29-17](https://user-images.githubusercontent.com/45543257/162554749-1b3feb62-a38d-4932-9f3f-511f8046330c.png)
The path/search bar width is inconsistent. Examples used here are Files and Web (version 41). Also to note, the back/forward buttons have a "frame" around them in Web, but no other apps seem to have this. 

It's the same in Maps and Image Viewer as well as some other apps, where the zoom in/out buttons have the same styling:
![Screenshot from 2022-04-09 15-36-01](https://user-images.githubusercontent.com/45543257/162554930-5d3ed602-d2e8-4dfb-bcc1-f83fe8a77332.png)
![Screenshot from 2022-04-09 15-37-27](https://user-images.githubusercontent.com/45543257/162554932-a64c2a97-c4cb-4df1-bef0-e57f4ef0424f.png)

**Comment by lassekongo83** [comment]
Unable to reproduce in webb 42. My buttons and entry bar have the same height.

Nautilus use custom styling for the back and forward buttons, something I'm considering removing, so those also will have a fill. Can't find an easy fix for the search bar height though.

I'm not quite sure what's wrong with image viewer. Looks fine to me.

**Comment by logant547** [comment]
Odd, maybe these issues are specifically related to Gnome 41.

**Comment by lassekongo83** [comment]
Could also be font and scaling settings.
