### ISSUE TITLE
Noticeably slower than adwaita

### ISSUE THREAD

**Issue by aunetx** [lassekongo83/adw-gtk3#9]
Hello, and thank you for this great theme! I hope this could be the official GTK3 theme at one point, as it does not make any sense not to have the same look and feel for gtk3 and gtk4+libadwaita apps...

However, this theme feels noticeably slower than the default adwaita theme, especially when moving/resizing apps. Do you have any idea where this could come from?

**Comment by lassekongo83** [comment]
I haven't noticed any slowness. I guess the box-shadow on the window decoration could be the issue.

```css
  box-shadow: 0 1px 3px 3px transparent,
              0 2px 8px 2px transparentize(black, 0.87),
              0 3px 20px 10px transparentize(black, 0.91),
              0 6px 32px 16px transparentize(black, 0.96),
              0 0 0 1px $_wm_border;
```

It's definitely larger than the old theme which use:

```css
  box-shadow: 0 3px 9px 1px transparentize(black, 0.5),
              0 0 0 1px $_wm_border;
```

**Comment by A6GibKm** [comment]
Note that the libadwaita theme uses transparency all over the place, this is extremely expensive to do on CPU (gtk3) but not so much in GPU (GTK 4)

**Comment by aunetx** [comment]
It definitively looks like it comes from the box-shadow, changing it to the old one it much quicker -- and does not affect the look imho

**Comment by aunetx** [comment]
Thanks!
