### ISSUE TITLE
Firefox rounded corner issue

### ISSUE THREAD

**Issue by larso0** [lassekongo83/adw-gtk3#92]
I'm using this theme installed from arch user repository. It is great to get a uniform look with GNOME. However there is a small issue where the rounded corners of firefox looks a bit odd:
![Screenshot from 2022-04-22 14-22-49](https://user-images.githubusercontent.com/6935136/164714813-37cc76d9-7da9-489d-8527-00216975103f.png)
It is mostly noticable when over a bright background.

**Comment by lassekongo83** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1509931
