### ISSUE TITLE
Gnome Extensions 41.5

### ISSUE THREAD

**Issue by svampkorg** [lassekongo83/adw-gtk3#93]
![image](https://user-images.githubusercontent.com/99117038/164993053-b3ed59dc-53d4-44eb-b41a-d298ada421a2.png)

Gnome Extensions not dark-themed. Using Manjaro Gnome edition. 
I also notice the rounded corners of the window are less rounded. Also switching to other dark themes does indeed theme Extensions properly. Take a look here for example:
![image](https://user-images.githubusercontent.com/99117038/164993169-d7c1a6eb-8fad-4f18-92ce-b992740fe1e0.png)
Anything I can do for this on my end? :eyes:

**Comment by lassekongo83** [comment]
Did you check this? https://github.com/lassekongo83/adw-gtk3#dark-theme-issues

But it's possible that it's a GTK-4 app. Then you'll need to install libadwaita as a GTK-4 theme. (Extensions 42 is a libadwaita app btw.) https://github.com/lassekongo83/adw-gtk3/issues/23#issuecomment-1030757624

**Comment by svampkorg** [comment]
> Did you check this? https://github.com/lassekongo83/adw-gtk3#dark-theme-issues
> 
> But it's possible that it's a GTK-4 app. Then you'll need to install libadwaita as a GTK-4 theme. [#23 (comment)](https://github.com/lassekongo83/adw-gtk3/issues/23#issuecomment-1030757624)

It worked! That last part with extracting the gtk4 from [diego-pvlk](https://github.com/diego-pvlk) worked! Thank you! :)
![image](https://user-images.githubusercontent.com/99117038/165031513-7306ba48-51dd-4474-961b-11ea623b3aea.png)
