### ISSUE TITLE
Popover paddings do not match

### ISSUE THREAD

**Issue by kk-mofux** [lassekongo83/adw-gtk3#95]
The paddings of popovers in adw-gtk3 are larger, thus not matching libadwaita. See screenshots for reference.

**libadwaita**:

![popover-padding-libadwaita](https://user-images.githubusercontent.com/7723079/165284178-2772be2f-17f5-4ceb-8861-325bbd65243b.png)

**adw-gtk3**:

![popover-padding-adw-gtk3](https://user-images.githubusercontent.com/7723079/165284208-e34ee4f9-21f2-4610-b2fc-f22ed9239181.png)

**Comment by lassekongo83** [comment]
The only way to fix this is to use a negative margin, which is risky and will most likely break some apps.

Add to `~/.config/gtk-3.0/gtk.css`:
```
popover.menu > stack { margin: -6px; }
```

Then test various apps with popovers and see if you notice any breakage.

**Comment by daudix-UFO** [comment]
I tested it, pretty stable, don't have any issues

**Comment by daudix-UFO** [comment]
Hello, I have tested this in a lot of gtk3 apps, and it works really stable, I haven't any issues, I think it can be included

**Comment by lassekongo83** [comment]
Closing this issue for now as I've currently put it into trial. Will revert if any issue occur.
