### ISSUE TITLE
[Question] Accent Colors

### ISSUE THREAD

**Issue by Nakamerica** [lassekongo83/adw-gtk3#98]
Hi, a wonderful piece of work first of all, feels good for people who want the new theme but do not want to update to gnome 42 just yet. 

I was wondering if there were any plans to add some accent colors (such as the one in the Ubuntu 22.04 perhaps?) to the theme. As we know, Gnome plans to add accent color support in Gnome 43, so if in any case this theme had added accent colors added in some future update, then it would look beautiful as well give us a spoiler of what's to come when gnome itself decides to add accent color theming :)

**Comment by lassekongo83** [comment]
It's possible to define the colors [the same way as libadwaita does](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_defaults.scss), to support recoloring. It's just a monumental time consuming task to convert every color. We would have to avoid using the `gtkalpha` function and too many transparent backgrounds for performance reasons, and each sass `darken`, `lighten`, etc would have to be re-written manually.

Then it's just a matter of the GTK4 implementation of a color API to be backwards compatible with GTK3. (Which I doubt that it will be.)

But with the libadwaita way of defining colors you would at least be able to change the colors in: `~/.config/gtk-3.0/gtk.css` and then add a line like for example: `@define-color accent_bg_color @green_4` (to use a green color from the theme's palette, but any color could be used.)

**Comment by Radical4ever** [comment]
i found out that using a gtk.css file in the `~/.config/gtk-4.0/gtk.css` you can force apps to use an accent color, so now i think its time to find a way to implement this on gtk3

**Comment by Radical4ever** [comment]
> i found out that using a gtk.css file in the `~/.config/gtk-4.0/gtk.css` you can force apps to use an accent color, so now i think its time to find a way to implement this on gtk3

I found a "solution" modifying the .css theme and changing de blue_3 color using text program to override the blue hex value i managed to make it to a different color!! and it works great on every app, this on gnome 41 would look awesome.
![Captura desde 2022-05-26 22-22-22](https://user-images.githubusercontent.com/83252104/170609681-7e241a85-a595-45e2-b8ab-1b26c3a6bb5f.png)
 :D

**Comment by Nakamerica** [comment]
> It's possible to define the colors [the same way as libadwaita does](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_defaults.scss) to support recoloring. It's just a monumental time consuming task to convert every color. We would have to avoid using the `gtkalpha` function and too many transparent backgrounds for performance reasons, and each sass `darken`, `lighten`, etc would have to be re-written manually.
> 
> Then it's just a matter of the GTK4 implementation of a color API to be backwards compatible with GTK3. (Which I doubt that it will be.)
> 
> But with the libadwaita way of defining colors you would at least be able to change the colors in `~/.config/gtk-3.0/gtk.css` and then add a line in it like: `@define-color accent_bg_color @green_4;` (to use a green color from the theme's palette, but any color could be used.)


I see, thank you for the explanation.

**Comment by lassekongo83** [comment]
The [color-rework branch](https://github.com/lassekongo83/adw-gtk3/tree/color-rework) should now be ready for testing: 
`git clone -b color-rework https://github.com/lassekongo83/adw-gtk3.git`

It should allow you to define colors the same way as seen [here](https://www.reddit.com/r/gnome/comments/tp3v7d/theming_in_libadwaita_is_pretty_nice/i28pug0/). (Just add them to `~/.config/gtk-3.0/gtk.css`)

There are still a lot of bugs to take care of though. Trying to convert every color without tanking performance may not make an exact match *(but close enough)* when using the same colors in `~/.config/gtk-4.0/gtk.css`. (Accent colors should be perfectly fine to change.)

**Comment by Radical4ever** [comment]
> The [color-rework branch](https://github.com/lassekongo83/adw-gtk3/tree/color-rework) should now be ready for testing: `git clone -b color-rework https://github.com/lassekongo83/adw-gtk3.git`
> 
> It should allow you to define colors the same way as seen [here](https://www.reddit.com/r/gnome/comments/tp3v7d/theming_in_libadwaita_is_pretty_nice/i28pug0/). (Just add them to `~/.config/gtk-3.0/gtk.css`)
> 
> There are still a lot of bugs to take care of though.

how do you exactly you make the gtk.css file to work along with the accent colors bc when i tried ir ir doesnt change the colors.

**Comment by lassekongo83** [comment]
I've updated the theme to support accent colors at least.

Add to: `~/.config/gtk-3.0/gtk.css`
```css
 /* replace @green_4 with any color you like */
@define-color accent_color @green_4;
@define-color accent_bg_color @green_4;
```
